package com.model;

public class Bumen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenMark
     *
     * @mbggenerated
     */
    private String bumenMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenMark1
     *
     * @mbggenerated
     */
    private String bumenMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenMark2
     *
     * @mbggenerated
     */
    private Integer bumenMark2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenId
     *
     * @return the value of t_bumen.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenId
     *
     * @param bumenId the value for t_bumen.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenName
     *
     * @return the value of t_bumen.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenName
     *
     * @param bumenName the value for t_bumen.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenMark
     *
     * @return the value of t_bumen.bumenMark
     *
     * @mbggenerated
     */
    public String getBumenMark() {
        return bumenMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenMark
     *
     * @param bumenMark the value for t_bumen.bumenMark
     *
     * @mbggenerated
     */
    public void setBumenMark(String bumenMark) {
        this.bumenMark = bumenMark == null ? null : bumenMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenMark1
     *
     * @return the value of t_bumen.bumenMark1
     *
     * @mbggenerated
     */
    public String getBumenMark1() {
        return bumenMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenMark1
     *
     * @param bumenMark1 the value for t_bumen.bumenMark1
     *
     * @mbggenerated
     */
    public void setBumenMark1(String bumenMark1) {
        this.bumenMark1 = bumenMark1 == null ? null : bumenMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenMark2
     *
     * @return the value of t_bumen.bumenMark2
     *
     * @mbggenerated
     */
    public Integer getBumenMark2() {
        return bumenMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenMark2
     *
     * @param bumenMark2 the value for t_bumen.bumenMark2
     *
     * @mbggenerated
     */
    public void setBumenMark2(Integer bumenMark2) {
        this.bumenMark2 = bumenMark2;
    }
}