package com.model;

import java.util.Date;

public class Shangpin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinId
     *
     * @mbggenerated
     */
    private Integer shangpinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinName
     *
     * @mbggenerated
     */
    private String shangpinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinMark
     *
     * @mbggenerated
     */
    private String shangpinMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinMark1
     *
     * @mbggenerated
     */
    private String shangpinMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinMark2
     *
     * @mbggenerated
     */
    private String shangpinMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinMark3
     *
     * @mbggenerated
     */
    private String shangpinMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinDate
     *
     * @mbggenerated
     */
    private Date shangpinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinDate1
     *
     * @mbggenerated
     */
    private Date shangpinDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinZong
     *
     * @mbggenerated
     */
    private Integer shangpinZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinJin
     *
     * @mbggenerated
     */
    private Double shangpinJin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinXiao
     *
     * @mbggenerated
     */
    private Double shangpinXiao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinLirun
     *
     * @mbggenerated
     */
    private Double shangpinLirun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinType
     *
     * @mbggenerated
     */
    private Integer shangpinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinType1
     *
     * @mbggenerated
     */
    private Integer shangpinType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinImg
     *
     * @mbggenerated
     */
    private String shangpinImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.shangpinImgName
     *
     * @mbggenerated
     */
    private String shangpinImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.sptypeId
     *
     * @mbggenerated
     */
    private Integer sptypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.sptypeName
     *
     * @mbggenerated
     */
    private String sptypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shangpin.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinId
     *
     * @return the value of t_shangpin.shangpinId
     *
     * @mbggenerated
     */
    public Integer getShangpinId() {
        return shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinId
     *
     * @param shangpinId the value for t_shangpin.shangpinId
     *
     * @mbggenerated
     */
    public void setShangpinId(Integer shangpinId) {
        this.shangpinId = shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinName
     *
     * @return the value of t_shangpin.shangpinName
     *
     * @mbggenerated
     */
    public String getShangpinName() {
        return shangpinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinName
     *
     * @param shangpinName the value for t_shangpin.shangpinName
     *
     * @mbggenerated
     */
    public void setShangpinName(String shangpinName) {
        this.shangpinName = shangpinName == null ? null : shangpinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinMark
     *
     * @return the value of t_shangpin.shangpinMark
     *
     * @mbggenerated
     */
    public String getShangpinMark() {
        return shangpinMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinMark
     *
     * @param shangpinMark the value for t_shangpin.shangpinMark
     *
     * @mbggenerated
     */
    public void setShangpinMark(String shangpinMark) {
        this.shangpinMark = shangpinMark == null ? null : shangpinMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinMark1
     *
     * @return the value of t_shangpin.shangpinMark1
     *
     * @mbggenerated
     */
    public String getShangpinMark1() {
        return shangpinMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinMark1
     *
     * @param shangpinMark1 the value for t_shangpin.shangpinMark1
     *
     * @mbggenerated
     */
    public void setShangpinMark1(String shangpinMark1) {
        this.shangpinMark1 = shangpinMark1 == null ? null : shangpinMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinMark2
     *
     * @return the value of t_shangpin.shangpinMark2
     *
     * @mbggenerated
     */
    public String getShangpinMark2() {
        return shangpinMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinMark2
     *
     * @param shangpinMark2 the value for t_shangpin.shangpinMark2
     *
     * @mbggenerated
     */
    public void setShangpinMark2(String shangpinMark2) {
        this.shangpinMark2 = shangpinMark2 == null ? null : shangpinMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinMark3
     *
     * @return the value of t_shangpin.shangpinMark3
     *
     * @mbggenerated
     */
    public String getShangpinMark3() {
        return shangpinMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinMark3
     *
     * @param shangpinMark3 the value for t_shangpin.shangpinMark3
     *
     * @mbggenerated
     */
    public void setShangpinMark3(String shangpinMark3) {
        this.shangpinMark3 = shangpinMark3 == null ? null : shangpinMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinDate
     *
     * @return the value of t_shangpin.shangpinDate
     *
     * @mbggenerated
     */
    public Date getShangpinDate() {
        return shangpinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinDate
     *
     * @param shangpinDate the value for t_shangpin.shangpinDate
     *
     * @mbggenerated
     */
    public void setShangpinDate(Date shangpinDate) {
        this.shangpinDate = shangpinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinDate1
     *
     * @return the value of t_shangpin.shangpinDate1
     *
     * @mbggenerated
     */
    public Date getShangpinDate1() {
        return shangpinDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinDate1
     *
     * @param shangpinDate1 the value for t_shangpin.shangpinDate1
     *
     * @mbggenerated
     */
    public void setShangpinDate1(Date shangpinDate1) {
        this.shangpinDate1 = shangpinDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinZong
     *
     * @return the value of t_shangpin.shangpinZong
     *
     * @mbggenerated
     */
    public Integer getShangpinZong() {
        return shangpinZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinZong
     *
     * @param shangpinZong the value for t_shangpin.shangpinZong
     *
     * @mbggenerated
     */
    public void setShangpinZong(Integer shangpinZong) {
        this.shangpinZong = shangpinZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinJin
     *
     * @return the value of t_shangpin.shangpinJin
     *
     * @mbggenerated
     */
    public Double getShangpinJin() {
        return shangpinJin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinJin
     *
     * @param shangpinJin the value for t_shangpin.shangpinJin
     *
     * @mbggenerated
     */
    public void setShangpinJin(Double shangpinJin) {
        this.shangpinJin = shangpinJin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinXiao
     *
     * @return the value of t_shangpin.shangpinXiao
     *
     * @mbggenerated
     */
    public Double getShangpinXiao() {
        return shangpinXiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinXiao
     *
     * @param shangpinXiao the value for t_shangpin.shangpinXiao
     *
     * @mbggenerated
     */
    public void setShangpinXiao(Double shangpinXiao) {
        this.shangpinXiao = shangpinXiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinLirun
     *
     * @return the value of t_shangpin.shangpinLirun
     *
     * @mbggenerated
     */
    public Double getShangpinLirun() {
        return shangpinLirun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinLirun
     *
     * @param shangpinLirun the value for t_shangpin.shangpinLirun
     *
     * @mbggenerated
     */
    public void setShangpinLirun(Double shangpinLirun) {
        this.shangpinLirun = shangpinLirun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinType
     *
     * @return the value of t_shangpin.shangpinType
     *
     * @mbggenerated
     */
    public Integer getShangpinType() {
        return shangpinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinType
     *
     * @param shangpinType the value for t_shangpin.shangpinType
     *
     * @mbggenerated
     */
    public void setShangpinType(Integer shangpinType) {
        this.shangpinType = shangpinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinType1
     *
     * @return the value of t_shangpin.shangpinType1
     *
     * @mbggenerated
     */
    public Integer getShangpinType1() {
        return shangpinType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinType1
     *
     * @param shangpinType1 the value for t_shangpin.shangpinType1
     *
     * @mbggenerated
     */
    public void setShangpinType1(Integer shangpinType1) {
        this.shangpinType1 = shangpinType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinImg
     *
     * @return the value of t_shangpin.shangpinImg
     *
     * @mbggenerated
     */
    public String getShangpinImg() {
        return shangpinImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinImg
     *
     * @param shangpinImg the value for t_shangpin.shangpinImg
     *
     * @mbggenerated
     */
    public void setShangpinImg(String shangpinImg) {
        this.shangpinImg = shangpinImg == null ? null : shangpinImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.shangpinImgName
     *
     * @return the value of t_shangpin.shangpinImgName
     *
     * @mbggenerated
     */
    public String getShangpinImgName() {
        return shangpinImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.shangpinImgName
     *
     * @param shangpinImgName the value for t_shangpin.shangpinImgName
     *
     * @mbggenerated
     */
    public void setShangpinImgName(String shangpinImgName) {
        this.shangpinImgName = shangpinImgName == null ? null : shangpinImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.sptypeId
     *
     * @return the value of t_shangpin.sptypeId
     *
     * @mbggenerated
     */
    public Integer getSptypeId() {
        return sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.sptypeId
     *
     * @param sptypeId the value for t_shangpin.sptypeId
     *
     * @mbggenerated
     */
    public void setSptypeId(Integer sptypeId) {
        this.sptypeId = sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.sptypeName
     *
     * @return the value of t_shangpin.sptypeName
     *
     * @mbggenerated
     */
    public String getSptypeName() {
        return sptypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.sptypeName
     *
     * @param sptypeName the value for t_shangpin.sptypeName
     *
     * @mbggenerated
     */
    public void setSptypeName(String sptypeName) {
        this.sptypeName = sptypeName == null ? null : sptypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.userId
     *
     * @return the value of t_shangpin.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.userId
     *
     * @param userId the value for t_shangpin.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.userName
     *
     * @return the value of t_shangpin.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.userName
     *
     * @param userName the value for t_shangpin.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.bumenId
     *
     * @return the value of t_shangpin.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.bumenId
     *
     * @param bumenId the value for t_shangpin.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.bumenName
     *
     * @return the value of t_shangpin.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.bumenName
     *
     * @param bumenName the value for t_shangpin.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.roleId
     *
     * @return the value of t_shangpin.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.roleId
     *
     * @param roleId the value for t_shangpin.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shangpin.roleName
     *
     * @return the value of t_shangpin.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shangpin.roleName
     *
     * @param roleName the value for t_shangpin.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}