package com.model;

import java.util.Date;

public class Spcangku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuId
     *
     * @mbggenerated
     */
    private Integer spcangkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuName
     *
     * @mbggenerated
     */
    private String spcangkuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuMark
     *
     * @mbggenerated
     */
    private String spcangkuMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuMark1
     *
     * @mbggenerated
     */
    private String spcangkuMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuMark2
     *
     * @mbggenerated
     */
    private String spcangkuMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuPhone
     *
     * @mbggenerated
     */
    private String spcangkuPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuDizhi
     *
     * @mbggenerated
     */
    private String spcangkuDizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuDate
     *
     * @mbggenerated
     */
    private Date spcangkuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuDate1
     *
     * @mbggenerated
     */
    private Date spcangkuDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuType
     *
     * @mbggenerated
     */
    private Integer spcangkuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spcangku.spcangkuType1
     *
     * @mbggenerated
     */
    private Integer spcangkuType1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuId
     *
     * @return the value of t_spcangku.spcangkuId
     *
     * @mbggenerated
     */
    public Integer getSpcangkuId() {
        return spcangkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuId
     *
     * @param spcangkuId the value for t_spcangku.spcangkuId
     *
     * @mbggenerated
     */
    public void setSpcangkuId(Integer spcangkuId) {
        this.spcangkuId = spcangkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuName
     *
     * @return the value of t_spcangku.spcangkuName
     *
     * @mbggenerated
     */
    public String getSpcangkuName() {
        return spcangkuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuName
     *
     * @param spcangkuName the value for t_spcangku.spcangkuName
     *
     * @mbggenerated
     */
    public void setSpcangkuName(String spcangkuName) {
        this.spcangkuName = spcangkuName == null ? null : spcangkuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuMark
     *
     * @return the value of t_spcangku.spcangkuMark
     *
     * @mbggenerated
     */
    public String getSpcangkuMark() {
        return spcangkuMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuMark
     *
     * @param spcangkuMark the value for t_spcangku.spcangkuMark
     *
     * @mbggenerated
     */
    public void setSpcangkuMark(String spcangkuMark) {
        this.spcangkuMark = spcangkuMark == null ? null : spcangkuMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuMark1
     *
     * @return the value of t_spcangku.spcangkuMark1
     *
     * @mbggenerated
     */
    public String getSpcangkuMark1() {
        return spcangkuMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuMark1
     *
     * @param spcangkuMark1 the value for t_spcangku.spcangkuMark1
     *
     * @mbggenerated
     */
    public void setSpcangkuMark1(String spcangkuMark1) {
        this.spcangkuMark1 = spcangkuMark1 == null ? null : spcangkuMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuMark2
     *
     * @return the value of t_spcangku.spcangkuMark2
     *
     * @mbggenerated
     */
    public String getSpcangkuMark2() {
        return spcangkuMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuMark2
     *
     * @param spcangkuMark2 the value for t_spcangku.spcangkuMark2
     *
     * @mbggenerated
     */
    public void setSpcangkuMark2(String spcangkuMark2) {
        this.spcangkuMark2 = spcangkuMark2 == null ? null : spcangkuMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuPhone
     *
     * @return the value of t_spcangku.spcangkuPhone
     *
     * @mbggenerated
     */
    public String getSpcangkuPhone() {
        return spcangkuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuPhone
     *
     * @param spcangkuPhone the value for t_spcangku.spcangkuPhone
     *
     * @mbggenerated
     */
    public void setSpcangkuPhone(String spcangkuPhone) {
        this.spcangkuPhone = spcangkuPhone == null ? null : spcangkuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuDizhi
     *
     * @return the value of t_spcangku.spcangkuDizhi
     *
     * @mbggenerated
     */
    public String getSpcangkuDizhi() {
        return spcangkuDizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuDizhi
     *
     * @param spcangkuDizhi the value for t_spcangku.spcangkuDizhi
     *
     * @mbggenerated
     */
    public void setSpcangkuDizhi(String spcangkuDizhi) {
        this.spcangkuDizhi = spcangkuDizhi == null ? null : spcangkuDizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuDate
     *
     * @return the value of t_spcangku.spcangkuDate
     *
     * @mbggenerated
     */
    public Date getSpcangkuDate() {
        return spcangkuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuDate
     *
     * @param spcangkuDate the value for t_spcangku.spcangkuDate
     *
     * @mbggenerated
     */
    public void setSpcangkuDate(Date spcangkuDate) {
        this.spcangkuDate = spcangkuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuDate1
     *
     * @return the value of t_spcangku.spcangkuDate1
     *
     * @mbggenerated
     */
    public Date getSpcangkuDate1() {
        return spcangkuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuDate1
     *
     * @param spcangkuDate1 the value for t_spcangku.spcangkuDate1
     *
     * @mbggenerated
     */
    public void setSpcangkuDate1(Date spcangkuDate1) {
        this.spcangkuDate1 = spcangkuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuType
     *
     * @return the value of t_spcangku.spcangkuType
     *
     * @mbggenerated
     */
    public Integer getSpcangkuType() {
        return spcangkuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuType
     *
     * @param spcangkuType the value for t_spcangku.spcangkuType
     *
     * @mbggenerated
     */
    public void setSpcangkuType(Integer spcangkuType) {
        this.spcangkuType = spcangkuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spcangku.spcangkuType1
     *
     * @return the value of t_spcangku.spcangkuType1
     *
     * @mbggenerated
     */
    public Integer getSpcangkuType1() {
        return spcangkuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spcangku.spcangkuType1
     *
     * @param spcangkuType1 the value for t_spcangku.spcangkuType1
     *
     * @mbggenerated
     */
    public void setSpcangkuType1(Integer spcangkuType1) {
        this.spcangkuType1 = spcangkuType1;
    }
}