package com.model;

import java.util.Date;

public class Spchu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuId
     *
     * @mbggenerated
     */
    private Integer spchuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuName
     *
     * @mbggenerated
     */
    private String spchuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuMark
     *
     * @mbggenerated
     */
    private String spchuMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuMark1
     *
     * @mbggenerated
     */
    private String spchuMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuMark2
     *
     * @mbggenerated
     */
    private String spchuMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuMark3
     *
     * @mbggenerated
     */
    private String spchuMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuDate
     *
     * @mbggenerated
     */
    private Date spchuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuDate1
     *
     * @mbggenerated
     */
    private Date spchuDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuZong
     *
     * @mbggenerated
     */
    private Integer spchuZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuJine
     *
     * @mbggenerated
     */
    private Double spchuJine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuZe
     *
     * @mbggenerated
     */
    private Double spchuZe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuType
     *
     * @mbggenerated
     */
    private Integer spchuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuType1
     *
     * @mbggenerated
     */
    private Integer spchuType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.shangpinId
     *
     * @mbggenerated
     */
    private Integer shangpinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.shangpinName
     *
     * @mbggenerated
     */
    private String shangpinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.sptypeId
     *
     * @mbggenerated
     */
    private Integer sptypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.sptypeName
     *
     * @mbggenerated
     */
    private String sptypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.yhbumenId
     *
     * @mbggenerated
     */
    private Integer yhbumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.yhbumenName
     *
     * @mbggenerated
     */
    private String yhbumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuImg
     *
     * @mbggenerated
     */
    private String spchuImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spchu.spchuImgName
     *
     * @mbggenerated
     */
    private String spchuImgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuId
     *
     * @return the value of t_spchu.spchuId
     *
     * @mbggenerated
     */
    public Integer getSpchuId() {
        return spchuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuId
     *
     * @param spchuId the value for t_spchu.spchuId
     *
     * @mbggenerated
     */
    public void setSpchuId(Integer spchuId) {
        this.spchuId = spchuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuName
     *
     * @return the value of t_spchu.spchuName
     *
     * @mbggenerated
     */
    public String getSpchuName() {
        return spchuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuName
     *
     * @param spchuName the value for t_spchu.spchuName
     *
     * @mbggenerated
     */
    public void setSpchuName(String spchuName) {
        this.spchuName = spchuName == null ? null : spchuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuMark
     *
     * @return the value of t_spchu.spchuMark
     *
     * @mbggenerated
     */
    public String getSpchuMark() {
        return spchuMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuMark
     *
     * @param spchuMark the value for t_spchu.spchuMark
     *
     * @mbggenerated
     */
    public void setSpchuMark(String spchuMark) {
        this.spchuMark = spchuMark == null ? null : spchuMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuMark1
     *
     * @return the value of t_spchu.spchuMark1
     *
     * @mbggenerated
     */
    public String getSpchuMark1() {
        return spchuMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuMark1
     *
     * @param spchuMark1 the value for t_spchu.spchuMark1
     *
     * @mbggenerated
     */
    public void setSpchuMark1(String spchuMark1) {
        this.spchuMark1 = spchuMark1 == null ? null : spchuMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuMark2
     *
     * @return the value of t_spchu.spchuMark2
     *
     * @mbggenerated
     */
    public String getSpchuMark2() {
        return spchuMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuMark2
     *
     * @param spchuMark2 the value for t_spchu.spchuMark2
     *
     * @mbggenerated
     */
    public void setSpchuMark2(String spchuMark2) {
        this.spchuMark2 = spchuMark2 == null ? null : spchuMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuMark3
     *
     * @return the value of t_spchu.spchuMark3
     *
     * @mbggenerated
     */
    public String getSpchuMark3() {
        return spchuMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuMark3
     *
     * @param spchuMark3 the value for t_spchu.spchuMark3
     *
     * @mbggenerated
     */
    public void setSpchuMark3(String spchuMark3) {
        this.spchuMark3 = spchuMark3 == null ? null : spchuMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuDate
     *
     * @return the value of t_spchu.spchuDate
     *
     * @mbggenerated
     */
    public Date getSpchuDate() {
        return spchuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuDate
     *
     * @param spchuDate the value for t_spchu.spchuDate
     *
     * @mbggenerated
     */
    public void setSpchuDate(Date spchuDate) {
        this.spchuDate = spchuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuDate1
     *
     * @return the value of t_spchu.spchuDate1
     *
     * @mbggenerated
     */
    public Date getSpchuDate1() {
        return spchuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuDate1
     *
     * @param spchuDate1 the value for t_spchu.spchuDate1
     *
     * @mbggenerated
     */
    public void setSpchuDate1(Date spchuDate1) {
        this.spchuDate1 = spchuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuZong
     *
     * @return the value of t_spchu.spchuZong
     *
     * @mbggenerated
     */
    public Integer getSpchuZong() {
        return spchuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuZong
     *
     * @param spchuZong the value for t_spchu.spchuZong
     *
     * @mbggenerated
     */
    public void setSpchuZong(Integer spchuZong) {
        this.spchuZong = spchuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuJine
     *
     * @return the value of t_spchu.spchuJine
     *
     * @mbggenerated
     */
    public Double getSpchuJine() {
        return spchuJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuJine
     *
     * @param spchuJine the value for t_spchu.spchuJine
     *
     * @mbggenerated
     */
    public void setSpchuJine(Double spchuJine) {
        this.spchuJine = spchuJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuZe
     *
     * @return the value of t_spchu.spchuZe
     *
     * @mbggenerated
     */
    public Double getSpchuZe() {
        return spchuZe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuZe
     *
     * @param spchuZe the value for t_spchu.spchuZe
     *
     * @mbggenerated
     */
    public void setSpchuZe(Double spchuZe) {
        this.spchuZe = spchuZe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuType
     *
     * @return the value of t_spchu.spchuType
     *
     * @mbggenerated
     */
    public Integer getSpchuType() {
        return spchuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuType
     *
     * @param spchuType the value for t_spchu.spchuType
     *
     * @mbggenerated
     */
    public void setSpchuType(Integer spchuType) {
        this.spchuType = spchuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuType1
     *
     * @return the value of t_spchu.spchuType1
     *
     * @mbggenerated
     */
    public Integer getSpchuType1() {
        return spchuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuType1
     *
     * @param spchuType1 the value for t_spchu.spchuType1
     *
     * @mbggenerated
     */
    public void setSpchuType1(Integer spchuType1) {
        this.spchuType1 = spchuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.shangpinId
     *
     * @return the value of t_spchu.shangpinId
     *
     * @mbggenerated
     */
    public Integer getShangpinId() {
        return shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.shangpinId
     *
     * @param shangpinId the value for t_spchu.shangpinId
     *
     * @mbggenerated
     */
    public void setShangpinId(Integer shangpinId) {
        this.shangpinId = shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.shangpinName
     *
     * @return the value of t_spchu.shangpinName
     *
     * @mbggenerated
     */
    public String getShangpinName() {
        return shangpinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.shangpinName
     *
     * @param shangpinName the value for t_spchu.shangpinName
     *
     * @mbggenerated
     */
    public void setShangpinName(String shangpinName) {
        this.shangpinName = shangpinName == null ? null : shangpinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.sptypeId
     *
     * @return the value of t_spchu.sptypeId
     *
     * @mbggenerated
     */
    public Integer getSptypeId() {
        return sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.sptypeId
     *
     * @param sptypeId the value for t_spchu.sptypeId
     *
     * @mbggenerated
     */
    public void setSptypeId(Integer sptypeId) {
        this.sptypeId = sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.sptypeName
     *
     * @return the value of t_spchu.sptypeName
     *
     * @mbggenerated
     */
    public String getSptypeName() {
        return sptypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.sptypeName
     *
     * @param sptypeName the value for t_spchu.sptypeName
     *
     * @mbggenerated
     */
    public void setSptypeName(String sptypeName) {
        this.sptypeName = sptypeName == null ? null : sptypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.yonghuId
     *
     * @return the value of t_spchu.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.yonghuId
     *
     * @param yonghuId the value for t_spchu.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.yonghuName
     *
     * @return the value of t_spchu.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.yonghuName
     *
     * @param yonghuName the value for t_spchu.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.yhroleId
     *
     * @return the value of t_spchu.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.yhroleId
     *
     * @param yhroleId the value for t_spchu.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.yhroleName
     *
     * @return the value of t_spchu.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.yhroleName
     *
     * @param yhroleName the value for t_spchu.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.yhbumenId
     *
     * @return the value of t_spchu.yhbumenId
     *
     * @mbggenerated
     */
    public Integer getYhbumenId() {
        return yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.yhbumenId
     *
     * @param yhbumenId the value for t_spchu.yhbumenId
     *
     * @mbggenerated
     */
    public void setYhbumenId(Integer yhbumenId) {
        this.yhbumenId = yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.yhbumenName
     *
     * @return the value of t_spchu.yhbumenName
     *
     * @mbggenerated
     */
    public String getYhbumenName() {
        return yhbumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.yhbumenName
     *
     * @param yhbumenName the value for t_spchu.yhbumenName
     *
     * @mbggenerated
     */
    public void setYhbumenName(String yhbumenName) {
        this.yhbumenName = yhbumenName == null ? null : yhbumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.userId
     *
     * @return the value of t_spchu.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.userId
     *
     * @param userId the value for t_spchu.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.userName
     *
     * @return the value of t_spchu.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.userName
     *
     * @param userName the value for t_spchu.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.bumenId
     *
     * @return the value of t_spchu.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.bumenId
     *
     * @param bumenId the value for t_spchu.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.bumenName
     *
     * @return the value of t_spchu.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.bumenName
     *
     * @param bumenName the value for t_spchu.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.roleId
     *
     * @return the value of t_spchu.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.roleId
     *
     * @param roleId the value for t_spchu.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.roleName
     *
     * @return the value of t_spchu.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.roleName
     *
     * @param roleName the value for t_spchu.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuImg
     *
     * @return the value of t_spchu.spchuImg
     *
     * @mbggenerated
     */
    public String getSpchuImg() {
        return spchuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuImg
     *
     * @param spchuImg the value for t_spchu.spchuImg
     *
     * @mbggenerated
     */
    public void setSpchuImg(String spchuImg) {
        this.spchuImg = spchuImg == null ? null : spchuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spchu.spchuImgName
     *
     * @return the value of t_spchu.spchuImgName
     *
     * @mbggenerated
     */
    public String getSpchuImgName() {
        return spchuImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spchu.spchuImgName
     *
     * @param spchuImgName the value for t_spchu.spchuImgName
     *
     * @mbggenerated
     */
    public void setSpchuImgName(String spchuImgName) {
        this.spchuImgName = spchuImgName == null ? null : spchuImgName.trim();
    }
}