package com.model;

import java.util.Date;

public class Spgys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysId
     *
     * @mbggenerated
     */
    private Integer spgysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysName
     *
     * @mbggenerated
     */
    private String spgysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysMark
     *
     * @mbggenerated
     */
    private String spgysMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysMark1
     *
     * @mbggenerated
     */
    private String spgysMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysMark2
     *
     * @mbggenerated
     */
    private String spgysMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysPhone
     *
     * @mbggenerated
     */
    private String spgysPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysDizhi
     *
     * @mbggenerated
     */
    private String spgysDizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysDate
     *
     * @mbggenerated
     */
    private Date spgysDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysDate1
     *
     * @mbggenerated
     */
    private Date spgysDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysType
     *
     * @mbggenerated
     */
    private Integer spgysType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spgys.spgysType1
     *
     * @mbggenerated
     */
    private Integer spgysType1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysId
     *
     * @return the value of t_spgys.spgysId
     *
     * @mbggenerated
     */
    public Integer getSpgysId() {
        return spgysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysId
     *
     * @param spgysId the value for t_spgys.spgysId
     *
     * @mbggenerated
     */
    public void setSpgysId(Integer spgysId) {
        this.spgysId = spgysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysName
     *
     * @return the value of t_spgys.spgysName
     *
     * @mbggenerated
     */
    public String getSpgysName() {
        return spgysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysName
     *
     * @param spgysName the value for t_spgys.spgysName
     *
     * @mbggenerated
     */
    public void setSpgysName(String spgysName) {
        this.spgysName = spgysName == null ? null : spgysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysMark
     *
     * @return the value of t_spgys.spgysMark
     *
     * @mbggenerated
     */
    public String getSpgysMark() {
        return spgysMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysMark
     *
     * @param spgysMark the value for t_spgys.spgysMark
     *
     * @mbggenerated
     */
    public void setSpgysMark(String spgysMark) {
        this.spgysMark = spgysMark == null ? null : spgysMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysMark1
     *
     * @return the value of t_spgys.spgysMark1
     *
     * @mbggenerated
     */
    public String getSpgysMark1() {
        return spgysMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysMark1
     *
     * @param spgysMark1 the value for t_spgys.spgysMark1
     *
     * @mbggenerated
     */
    public void setSpgysMark1(String spgysMark1) {
        this.spgysMark1 = spgysMark1 == null ? null : spgysMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysMark2
     *
     * @return the value of t_spgys.spgysMark2
     *
     * @mbggenerated
     */
    public String getSpgysMark2() {
        return spgysMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysMark2
     *
     * @param spgysMark2 the value for t_spgys.spgysMark2
     *
     * @mbggenerated
     */
    public void setSpgysMark2(String spgysMark2) {
        this.spgysMark2 = spgysMark2 == null ? null : spgysMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysPhone
     *
     * @return the value of t_spgys.spgysPhone
     *
     * @mbggenerated
     */
    public String getSpgysPhone() {
        return spgysPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysPhone
     *
     * @param spgysPhone the value for t_spgys.spgysPhone
     *
     * @mbggenerated
     */
    public void setSpgysPhone(String spgysPhone) {
        this.spgysPhone = spgysPhone == null ? null : spgysPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysDizhi
     *
     * @return the value of t_spgys.spgysDizhi
     *
     * @mbggenerated
     */
    public String getSpgysDizhi() {
        return spgysDizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysDizhi
     *
     * @param spgysDizhi the value for t_spgys.spgysDizhi
     *
     * @mbggenerated
     */
    public void setSpgysDizhi(String spgysDizhi) {
        this.spgysDizhi = spgysDizhi == null ? null : spgysDizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysDate
     *
     * @return the value of t_spgys.spgysDate
     *
     * @mbggenerated
     */
    public Date getSpgysDate() {
        return spgysDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysDate
     *
     * @param spgysDate the value for t_spgys.spgysDate
     *
     * @mbggenerated
     */
    public void setSpgysDate(Date spgysDate) {
        this.spgysDate = spgysDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysDate1
     *
     * @return the value of t_spgys.spgysDate1
     *
     * @mbggenerated
     */
    public Date getSpgysDate1() {
        return spgysDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysDate1
     *
     * @param spgysDate1 the value for t_spgys.spgysDate1
     *
     * @mbggenerated
     */
    public void setSpgysDate1(Date spgysDate1) {
        this.spgysDate1 = spgysDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysType
     *
     * @return the value of t_spgys.spgysType
     *
     * @mbggenerated
     */
    public Integer getSpgysType() {
        return spgysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysType
     *
     * @param spgysType the value for t_spgys.spgysType
     *
     * @mbggenerated
     */
    public void setSpgysType(Integer spgysType) {
        this.spgysType = spgysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spgys.spgysType1
     *
     * @return the value of t_spgys.spgysType1
     *
     * @mbggenerated
     */
    public Integer getSpgysType1() {
        return spgysType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spgys.spgysType1
     *
     * @param spgysType1 the value for t_spgys.spgysType1
     *
     * @mbggenerated
     */
    public void setSpgysType1(Integer spgysType1) {
        this.spgysType1 = spgysType1;
    }
}