package com.model;

import java.util.Date;

public class Spjin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinId
     *
     * @mbggenerated
     */
    private Integer spjinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinName
     *
     * @mbggenerated
     */
    private String spjinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinMark
     *
     * @mbggenerated
     */
    private String spjinMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinMark1
     *
     * @mbggenerated
     */
    private String spjinMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinMark2
     *
     * @mbggenerated
     */
    private String spjinMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinMark3
     *
     * @mbggenerated
     */
    private String spjinMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinDate
     *
     * @mbggenerated
     */
    private Date spjinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinDate1
     *
     * @mbggenerated
     */
    private Date spjinDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinZong
     *
     * @mbggenerated
     */
    private Integer spjinZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinJine
     *
     * @mbggenerated
     */
    private Double spjinJine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinZe
     *
     * @mbggenerated
     */
    private Double spjinZe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinType
     *
     * @mbggenerated
     */
    private Integer spjinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinType1
     *
     * @mbggenerated
     */
    private Integer spjinType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.shangpinId
     *
     * @mbggenerated
     */
    private Integer shangpinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.shangpinName
     *
     * @mbggenerated
     */
    private String shangpinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.sptypeId
     *
     * @mbggenerated
     */
    private Integer sptypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.sptypeName
     *
     * @mbggenerated
     */
    private String sptypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spcangkuId
     *
     * @mbggenerated
     */
    private Integer spcangkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spcangkuName
     *
     * @mbggenerated
     */
    private String spcangkuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spgysId
     *
     * @mbggenerated
     */
    private Integer spgysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spgysName
     *
     * @mbggenerated
     */
    private String spgysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinImg
     *
     * @mbggenerated
     */
    private String spjinImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spjin.spjinImgName
     *
     * @mbggenerated
     */
    private String spjinImgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinId
     *
     * @return the value of t_spjin.spjinId
     *
     * @mbggenerated
     */
    public Integer getSpjinId() {
        return spjinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinId
     *
     * @param spjinId the value for t_spjin.spjinId
     *
     * @mbggenerated
     */
    public void setSpjinId(Integer spjinId) {
        this.spjinId = spjinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinName
     *
     * @return the value of t_spjin.spjinName
     *
     * @mbggenerated
     */
    public String getSpjinName() {
        return spjinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinName
     *
     * @param spjinName the value for t_spjin.spjinName
     *
     * @mbggenerated
     */
    public void setSpjinName(String spjinName) {
        this.spjinName = spjinName == null ? null : spjinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinMark
     *
     * @return the value of t_spjin.spjinMark
     *
     * @mbggenerated
     */
    public String getSpjinMark() {
        return spjinMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinMark
     *
     * @param spjinMark the value for t_spjin.spjinMark
     *
     * @mbggenerated
     */
    public void setSpjinMark(String spjinMark) {
        this.spjinMark = spjinMark == null ? null : spjinMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinMark1
     *
     * @return the value of t_spjin.spjinMark1
     *
     * @mbggenerated
     */
    public String getSpjinMark1() {
        return spjinMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinMark1
     *
     * @param spjinMark1 the value for t_spjin.spjinMark1
     *
     * @mbggenerated
     */
    public void setSpjinMark1(String spjinMark1) {
        this.spjinMark1 = spjinMark1 == null ? null : spjinMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinMark2
     *
     * @return the value of t_spjin.spjinMark2
     *
     * @mbggenerated
     */
    public String getSpjinMark2() {
        return spjinMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinMark2
     *
     * @param spjinMark2 the value for t_spjin.spjinMark2
     *
     * @mbggenerated
     */
    public void setSpjinMark2(String spjinMark2) {
        this.spjinMark2 = spjinMark2 == null ? null : spjinMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinMark3
     *
     * @return the value of t_spjin.spjinMark3
     *
     * @mbggenerated
     */
    public String getSpjinMark3() {
        return spjinMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinMark3
     *
     * @param spjinMark3 the value for t_spjin.spjinMark3
     *
     * @mbggenerated
     */
    public void setSpjinMark3(String spjinMark3) {
        this.spjinMark3 = spjinMark3 == null ? null : spjinMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinDate
     *
     * @return the value of t_spjin.spjinDate
     *
     * @mbggenerated
     */
    public Date getSpjinDate() {
        return spjinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinDate
     *
     * @param spjinDate the value for t_spjin.spjinDate
     *
     * @mbggenerated
     */
    public void setSpjinDate(Date spjinDate) {
        this.spjinDate = spjinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinDate1
     *
     * @return the value of t_spjin.spjinDate1
     *
     * @mbggenerated
     */
    public Date getSpjinDate1() {
        return spjinDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinDate1
     *
     * @param spjinDate1 the value for t_spjin.spjinDate1
     *
     * @mbggenerated
     */
    public void setSpjinDate1(Date spjinDate1) {
        this.spjinDate1 = spjinDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinZong
     *
     * @return the value of t_spjin.spjinZong
     *
     * @mbggenerated
     */
    public Integer getSpjinZong() {
        return spjinZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinZong
     *
     * @param spjinZong the value for t_spjin.spjinZong
     *
     * @mbggenerated
     */
    public void setSpjinZong(Integer spjinZong) {
        this.spjinZong = spjinZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinJine
     *
     * @return the value of t_spjin.spjinJine
     *
     * @mbggenerated
     */
    public Double getSpjinJine() {
        return spjinJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinJine
     *
     * @param spjinJine the value for t_spjin.spjinJine
     *
     * @mbggenerated
     */
    public void setSpjinJine(Double spjinJine) {
        this.spjinJine = spjinJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinZe
     *
     * @return the value of t_spjin.spjinZe
     *
     * @mbggenerated
     */
    public Double getSpjinZe() {
        return spjinZe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinZe
     *
     * @param spjinZe the value for t_spjin.spjinZe
     *
     * @mbggenerated
     */
    public void setSpjinZe(Double spjinZe) {
        this.spjinZe = spjinZe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinType
     *
     * @return the value of t_spjin.spjinType
     *
     * @mbggenerated
     */
    public Integer getSpjinType() {
        return spjinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinType
     *
     * @param spjinType the value for t_spjin.spjinType
     *
     * @mbggenerated
     */
    public void setSpjinType(Integer spjinType) {
        this.spjinType = spjinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinType1
     *
     * @return the value of t_spjin.spjinType1
     *
     * @mbggenerated
     */
    public Integer getSpjinType1() {
        return spjinType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinType1
     *
     * @param spjinType1 the value for t_spjin.spjinType1
     *
     * @mbggenerated
     */
    public void setSpjinType1(Integer spjinType1) {
        this.spjinType1 = spjinType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.shangpinId
     *
     * @return the value of t_spjin.shangpinId
     *
     * @mbggenerated
     */
    public Integer getShangpinId() {
        return shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.shangpinId
     *
     * @param shangpinId the value for t_spjin.shangpinId
     *
     * @mbggenerated
     */
    public void setShangpinId(Integer shangpinId) {
        this.shangpinId = shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.shangpinName
     *
     * @return the value of t_spjin.shangpinName
     *
     * @mbggenerated
     */
    public String getShangpinName() {
        return shangpinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.shangpinName
     *
     * @param shangpinName the value for t_spjin.shangpinName
     *
     * @mbggenerated
     */
    public void setShangpinName(String shangpinName) {
        this.shangpinName = shangpinName == null ? null : shangpinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.sptypeId
     *
     * @return the value of t_spjin.sptypeId
     *
     * @mbggenerated
     */
    public Integer getSptypeId() {
        return sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.sptypeId
     *
     * @param sptypeId the value for t_spjin.sptypeId
     *
     * @mbggenerated
     */
    public void setSptypeId(Integer sptypeId) {
        this.sptypeId = sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.sptypeName
     *
     * @return the value of t_spjin.sptypeName
     *
     * @mbggenerated
     */
    public String getSptypeName() {
        return sptypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.sptypeName
     *
     * @param sptypeName the value for t_spjin.sptypeName
     *
     * @mbggenerated
     */
    public void setSptypeName(String sptypeName) {
        this.sptypeName = sptypeName == null ? null : sptypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spcangkuId
     *
     * @return the value of t_spjin.spcangkuId
     *
     * @mbggenerated
     */
    public Integer getSpcangkuId() {
        return spcangkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spcangkuId
     *
     * @param spcangkuId the value for t_spjin.spcangkuId
     *
     * @mbggenerated
     */
    public void setSpcangkuId(Integer spcangkuId) {
        this.spcangkuId = spcangkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spcangkuName
     *
     * @return the value of t_spjin.spcangkuName
     *
     * @mbggenerated
     */
    public String getSpcangkuName() {
        return spcangkuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spcangkuName
     *
     * @param spcangkuName the value for t_spjin.spcangkuName
     *
     * @mbggenerated
     */
    public void setSpcangkuName(String spcangkuName) {
        this.spcangkuName = spcangkuName == null ? null : spcangkuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spgysId
     *
     * @return the value of t_spjin.spgysId
     *
     * @mbggenerated
     */
    public Integer getSpgysId() {
        return spgysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spgysId
     *
     * @param spgysId the value for t_spjin.spgysId
     *
     * @mbggenerated
     */
    public void setSpgysId(Integer spgysId) {
        this.spgysId = spgysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spgysName
     *
     * @return the value of t_spjin.spgysName
     *
     * @mbggenerated
     */
    public String getSpgysName() {
        return spgysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spgysName
     *
     * @param spgysName the value for t_spjin.spgysName
     *
     * @mbggenerated
     */
    public void setSpgysName(String spgysName) {
        this.spgysName = spgysName == null ? null : spgysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.userId
     *
     * @return the value of t_spjin.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.userId
     *
     * @param userId the value for t_spjin.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.userName
     *
     * @return the value of t_spjin.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.userName
     *
     * @param userName the value for t_spjin.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.bumenId
     *
     * @return the value of t_spjin.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.bumenId
     *
     * @param bumenId the value for t_spjin.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.bumenName
     *
     * @return the value of t_spjin.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.bumenName
     *
     * @param bumenName the value for t_spjin.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.roleId
     *
     * @return the value of t_spjin.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.roleId
     *
     * @param roleId the value for t_spjin.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.roleName
     *
     * @return the value of t_spjin.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.roleName
     *
     * @param roleName the value for t_spjin.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinImg
     *
     * @return the value of t_spjin.spjinImg
     *
     * @mbggenerated
     */
    public String getSpjinImg() {
        return spjinImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinImg
     *
     * @param spjinImg the value for t_spjin.spjinImg
     *
     * @mbggenerated
     */
    public void setSpjinImg(String spjinImg) {
        this.spjinImg = spjinImg == null ? null : spjinImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spjin.spjinImgName
     *
     * @return the value of t_spjin.spjinImgName
     *
     * @mbggenerated
     */
    public String getSpjinImgName() {
        return spjinImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spjin.spjinImgName
     *
     * @param spjinImgName the value for t_spjin.spjinImgName
     *
     * @mbggenerated
     */
    public void setSpjinImgName(String spjinImgName) {
        this.spjinImgName = spjinImgName == null ? null : spjinImgName.trim();
    }
}