package com.model;

public class Sptype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sptype.sptypeId
     *
     * @mbggenerated
     */
    private Integer sptypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sptype.sptypeName
     *
     * @mbggenerated
     */
    private String sptypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sptype.sptypeMark
     *
     * @mbggenerated
     */
    private String sptypeMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sptype.sptypeMark1
     *
     * @mbggenerated
     */
    private String sptypeMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sptype.sptypeMark2
     *
     * @mbggenerated
     */
    private Integer sptypeMark2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sptype.sptypeId
     *
     * @return the value of t_sptype.sptypeId
     *
     * @mbggenerated
     */
    public Integer getSptypeId() {
        return sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sptype.sptypeId
     *
     * @param sptypeId the value for t_sptype.sptypeId
     *
     * @mbggenerated
     */
    public void setSptypeId(Integer sptypeId) {
        this.sptypeId = sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sptype.sptypeName
     *
     * @return the value of t_sptype.sptypeName
     *
     * @mbggenerated
     */
    public String getSptypeName() {
        return sptypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sptype.sptypeName
     *
     * @param sptypeName the value for t_sptype.sptypeName
     *
     * @mbggenerated
     */
    public void setSptypeName(String sptypeName) {
        this.sptypeName = sptypeName == null ? null : sptypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sptype.sptypeMark
     *
     * @return the value of t_sptype.sptypeMark
     *
     * @mbggenerated
     */
    public String getSptypeMark() {
        return sptypeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sptype.sptypeMark
     *
     * @param sptypeMark the value for t_sptype.sptypeMark
     *
     * @mbggenerated
     */
    public void setSptypeMark(String sptypeMark) {
        this.sptypeMark = sptypeMark == null ? null : sptypeMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sptype.sptypeMark1
     *
     * @return the value of t_sptype.sptypeMark1
     *
     * @mbggenerated
     */
    public String getSptypeMark1() {
        return sptypeMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sptype.sptypeMark1
     *
     * @param sptypeMark1 the value for t_sptype.sptypeMark1
     *
     * @mbggenerated
     */
    public void setSptypeMark1(String sptypeMark1) {
        this.sptypeMark1 = sptypeMark1 == null ? null : sptypeMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sptype.sptypeMark2
     *
     * @return the value of t_sptype.sptypeMark2
     *
     * @mbggenerated
     */
    public Integer getSptypeMark2() {
        return sptypeMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sptype.sptypeMark2
     *
     * @param sptypeMark2 the value for t_sptype.sptypeMark2
     *
     * @mbggenerated
     */
    public void setSptypeMark2(Integer sptypeMark2) {
        this.sptypeMark2 = sptypeMark2;
    }
}