package com.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userId
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userName
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userPassword
	 * @mbggenerated
	 */
	private String userPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userXingming
	 * @mbggenerated
	 */
	private String userXingming;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userSex
	 * @mbggenerated
	 */
	private Integer userSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userAge
	 * @mbggenerated
	 */
	private Integer userAge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userPhone
	 * @mbggenerated
	 */
	private String userPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userMark1
	 * @mbggenerated
	 */
	private String userMark1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userMark2
	 * @mbggenerated
	 */
	private String userMark2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userMark3
	 * @mbggenerated
	 */
	private String userMark3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userMark4
	 * @mbggenerated
	 */
	private String userMark4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userDate1
	 * @mbggenerated
	 */
	private Date userDate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userDate2
	 * @mbggenerated
	 */
	private Date userDate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userType1
	 * @mbggenerated
	 */
	private Integer userType1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userType2
	 * @mbggenerated
	 */
	private Integer userType2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userImg
	 * @mbggenerated
	 */
	private String userImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userImgName
	 * @mbggenerated
	 */
	private String userImgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.roleId
	 * @mbggenerated
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.roleName
	 * @mbggenerated
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.bumenId
	 * @mbggenerated
	 */
	private Integer bumenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.bumenName
	 * @mbggenerated
	 */
	private String bumenName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userId
	 * @return  the value of t_user.userId
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userId
	 * @param userId  the value for t_user.userId
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userName
	 * @return  the value of t_user.userName
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userName
	 * @param userName  the value for t_user.userName
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userPassword
	 * @return  the value of t_user.userPassword
	 * @mbggenerated
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userPassword
	 * @param userPassword  the value for t_user.userPassword
	 * @mbggenerated
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword == null ? null : userPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userXingming
	 * @return  the value of t_user.userXingming
	 * @mbggenerated
	 */
	public String getUserXingming() {
		return userXingming;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userXingming
	 * @param userXingming  the value for t_user.userXingming
	 * @mbggenerated
	 */
	public void setUserXingming(String userXingming) {
		this.userXingming = userXingming == null ? null : userXingming.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userSex
	 * @return  the value of t_user.userSex
	 * @mbggenerated
	 */
	public Integer getUserSex() {
		return userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userSex
	 * @param userSex  the value for t_user.userSex
	 * @mbggenerated
	 */
	public void setUserSex(Integer userSex) {
		this.userSex = userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userAge
	 * @return  the value of t_user.userAge
	 * @mbggenerated
	 */
	public Integer getUserAge() {
		return userAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userAge
	 * @param userAge  the value for t_user.userAge
	 * @mbggenerated
	 */
	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userPhone
	 * @return  the value of t_user.userPhone
	 * @mbggenerated
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userPhone
	 * @param userPhone  the value for t_user.userPhone
	 * @mbggenerated
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone == null ? null : userPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userMark1
	 * @return  the value of t_user.userMark1
	 * @mbggenerated
	 */
	public String getUserMark1() {
		return userMark1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userMark1
	 * @param userMark1  the value for t_user.userMark1
	 * @mbggenerated
	 */
	public void setUserMark1(String userMark1) {
		this.userMark1 = userMark1 == null ? null : userMark1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userMark2
	 * @return  the value of t_user.userMark2
	 * @mbggenerated
	 */
	public String getUserMark2() {
		return userMark2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userMark2
	 * @param userMark2  the value for t_user.userMark2
	 * @mbggenerated
	 */
	public void setUserMark2(String userMark2) {
		this.userMark2 = userMark2 == null ? null : userMark2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userMark3
	 * @return  the value of t_user.userMark3
	 * @mbggenerated
	 */
	public String getUserMark3() {
		return userMark3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userMark3
	 * @param userMark3  the value for t_user.userMark3
	 * @mbggenerated
	 */
	public void setUserMark3(String userMark3) {
		this.userMark3 = userMark3 == null ? null : userMark3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userMark4
	 * @return  the value of t_user.userMark4
	 * @mbggenerated
	 */
	public String getUserMark4() {
		return userMark4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userMark4
	 * @param userMark4  the value for t_user.userMark4
	 * @mbggenerated
	 */
	public void setUserMark4(String userMark4) {
		this.userMark4 = userMark4 == null ? null : userMark4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userDate1
	 * @return  the value of t_user.userDate1
	 * @mbggenerated
	 */
	public Date getUserDate1() {
		return userDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userDate1
	 * @param userDate1  the value for t_user.userDate1
	 * @mbggenerated
	 */
	public void setUserDate1(Date userDate1) {
		this.userDate1 = userDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userDate2
	 * @return  the value of t_user.userDate2
	 * @mbggenerated
	 */
	public Date getUserDate2() {
		return userDate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userDate2
	 * @param userDate2  the value for t_user.userDate2
	 * @mbggenerated
	 */
	public void setUserDate2(Date userDate2) {
		this.userDate2 = userDate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userType1
	 * @return  the value of t_user.userType1
	 * @mbggenerated
	 */
	public Integer getUserType1() {
		return userType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userType1
	 * @param userType1  the value for t_user.userType1
	 * @mbggenerated
	 */
	public void setUserType1(Integer userType1) {
		this.userType1 = userType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userType2
	 * @return  the value of t_user.userType2
	 * @mbggenerated
	 */
	public Integer getUserType2() {
		return userType2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userType2
	 * @param userType2  the value for t_user.userType2
	 * @mbggenerated
	 */
	public void setUserType2(Integer userType2) {
		this.userType2 = userType2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userImg
	 * @return  the value of t_user.userImg
	 * @mbggenerated
	 */
	public String getUserImg() {
		return userImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userImg
	 * @param userImg  the value for t_user.userImg
	 * @mbggenerated
	 */
	public void setUserImg(String userImg) {
		this.userImg = userImg == null ? null : userImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userImgName
	 * @return  the value of t_user.userImgName
	 * @mbggenerated
	 */
	public String getUserImgName() {
		return userImgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userImgName
	 * @param userImgName  the value for t_user.userImgName
	 * @mbggenerated
	 */
	public void setUserImgName(String userImgName) {
		this.userImgName = userImgName == null ? null : userImgName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.roleId
	 * @return  the value of t_user.roleId
	 * @mbggenerated
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.roleId
	 * @param roleId  the value for t_user.roleId
	 * @mbggenerated
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.roleName
	 * @return  the value of t_user.roleName
	 * @mbggenerated
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.roleName
	 * @param roleName  the value for t_user.roleName
	 * @mbggenerated
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.bumenId
	 * @return  the value of t_user.bumenId
	 * @mbggenerated
	 */
	public Integer getBumenId() {
		return bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.bumenId
	 * @param bumenId  the value for t_user.bumenId
	 * @mbggenerated
	 */
	public void setBumenId(Integer bumenId) {
		this.bumenId = bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.bumenName
	 * @return  the value of t_user.bumenName
	 * @mbggenerated
	 */
	public String getBumenName() {
		return bumenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.bumenName
	 * @param bumenName  the value for t_user.bumenName
	 * @mbggenerated
	 */
	public void setBumenName(String bumenName) {
		this.bumenName = bumenName == null ? null : bumenName.trim();
	}
}