package com.model;

import java.util.Date;

public class Utaolun {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunId
	 * @mbggenerated
	 */
	private Integer utaolunId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunName
	 * @mbggenerated
	 */
	private String utaolunName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunMark
	 * @mbggenerated
	 */
	private String utaolunMark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunMark1
	 * @mbggenerated
	 */
	private String utaolunMark1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunMark2
	 * @mbggenerated
	 */
	private String utaolunMark2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunImg
	 * @mbggenerated
	 */
	private String utaolunImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunImgName
	 * @mbggenerated
	 */
	private String utaolunImgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunDate
	 * @mbggenerated
	 */
	private Date utaolunDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunDate1
	 * @mbggenerated
	 */
	private Date utaolunDate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunType
	 * @mbggenerated
	 */
	private Integer utaolunType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.utaolunType1
	 * @mbggenerated
	 */
	private Integer utaolunType1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.userId
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.userName
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.bumenId
	 * @mbggenerated
	 */
	private Integer bumenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.bumenName
	 * @mbggenerated
	 */
	private String bumenName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.yonghuId
	 * @mbggenerated
	 */
	private Integer yonghuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.yonghuName
	 * @mbggenerated
	 */
	private String yonghuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.yhbumenId
	 * @mbggenerated
	 */
	private Integer yhbumenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_utaolun.yhbumenName
	 * @mbggenerated
	 */
	private String yhbumenName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunId
	 * @return  the value of t_utaolun.utaolunId
	 * @mbggenerated
	 */
	public Integer getUtaolunId() {
		return utaolunId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunId
	 * @param utaolunId  the value for t_utaolun.utaolunId
	 * @mbggenerated
	 */
	public void setUtaolunId(Integer utaolunId) {
		this.utaolunId = utaolunId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunName
	 * @return  the value of t_utaolun.utaolunName
	 * @mbggenerated
	 */
	public String getUtaolunName() {
		return utaolunName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunName
	 * @param utaolunName  the value for t_utaolun.utaolunName
	 * @mbggenerated
	 */
	public void setUtaolunName(String utaolunName) {
		this.utaolunName = utaolunName == null ? null : utaolunName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunMark
	 * @return  the value of t_utaolun.utaolunMark
	 * @mbggenerated
	 */
	public String getUtaolunMark() {
		return utaolunMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunMark
	 * @param utaolunMark  the value for t_utaolun.utaolunMark
	 * @mbggenerated
	 */
	public void setUtaolunMark(String utaolunMark) {
		this.utaolunMark = utaolunMark == null ? null : utaolunMark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunMark1
	 * @return  the value of t_utaolun.utaolunMark1
	 * @mbggenerated
	 */
	public String getUtaolunMark1() {
		return utaolunMark1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunMark1
	 * @param utaolunMark1  the value for t_utaolun.utaolunMark1
	 * @mbggenerated
	 */
	public void setUtaolunMark1(String utaolunMark1) {
		this.utaolunMark1 = utaolunMark1 == null ? null : utaolunMark1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunMark2
	 * @return  the value of t_utaolun.utaolunMark2
	 * @mbggenerated
	 */
	public String getUtaolunMark2() {
		return utaolunMark2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunMark2
	 * @param utaolunMark2  the value for t_utaolun.utaolunMark2
	 * @mbggenerated
	 */
	public void setUtaolunMark2(String utaolunMark2) {
		this.utaolunMark2 = utaolunMark2 == null ? null : utaolunMark2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunImg
	 * @return  the value of t_utaolun.utaolunImg
	 * @mbggenerated
	 */
	public String getUtaolunImg() {
		return utaolunImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunImg
	 * @param utaolunImg  the value for t_utaolun.utaolunImg
	 * @mbggenerated
	 */
	public void setUtaolunImg(String utaolunImg) {
		this.utaolunImg = utaolunImg == null ? null : utaolunImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunImgName
	 * @return  the value of t_utaolun.utaolunImgName
	 * @mbggenerated
	 */
	public String getUtaolunImgName() {
		return utaolunImgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunImgName
	 * @param utaolunImgName  the value for t_utaolun.utaolunImgName
	 * @mbggenerated
	 */
	public void setUtaolunImgName(String utaolunImgName) {
		this.utaolunImgName = utaolunImgName == null ? null : utaolunImgName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunDate
	 * @return  the value of t_utaolun.utaolunDate
	 * @mbggenerated
	 */
	public Date getUtaolunDate() {
		return utaolunDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunDate
	 * @param utaolunDate  the value for t_utaolun.utaolunDate
	 * @mbggenerated
	 */
	public void setUtaolunDate(Date utaolunDate) {
		this.utaolunDate = utaolunDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunDate1
	 * @return  the value of t_utaolun.utaolunDate1
	 * @mbggenerated
	 */
	public Date getUtaolunDate1() {
		return utaolunDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunDate1
	 * @param utaolunDate1  the value for t_utaolun.utaolunDate1
	 * @mbggenerated
	 */
	public void setUtaolunDate1(Date utaolunDate1) {
		this.utaolunDate1 = utaolunDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunType
	 * @return  the value of t_utaolun.utaolunType
	 * @mbggenerated
	 */
	public Integer getUtaolunType() {
		return utaolunType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunType
	 * @param utaolunType  the value for t_utaolun.utaolunType
	 * @mbggenerated
	 */
	public void setUtaolunType(Integer utaolunType) {
		this.utaolunType = utaolunType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.utaolunType1
	 * @return  the value of t_utaolun.utaolunType1
	 * @mbggenerated
	 */
	public Integer getUtaolunType1() {
		return utaolunType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.utaolunType1
	 * @param utaolunType1  the value for t_utaolun.utaolunType1
	 * @mbggenerated
	 */
	public void setUtaolunType1(Integer utaolunType1) {
		this.utaolunType1 = utaolunType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.userId
	 * @return  the value of t_utaolun.userId
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.userId
	 * @param userId  the value for t_utaolun.userId
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.userName
	 * @return  the value of t_utaolun.userName
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.userName
	 * @param userName  the value for t_utaolun.userName
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.bumenId
	 * @return  the value of t_utaolun.bumenId
	 * @mbggenerated
	 */
	public Integer getBumenId() {
		return bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.bumenId
	 * @param bumenId  the value for t_utaolun.bumenId
	 * @mbggenerated
	 */
	public void setBumenId(Integer bumenId) {
		this.bumenId = bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.bumenName
	 * @return  the value of t_utaolun.bumenName
	 * @mbggenerated
	 */
	public String getBumenName() {
		return bumenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.bumenName
	 * @param bumenName  the value for t_utaolun.bumenName
	 * @mbggenerated
	 */
	public void setBumenName(String bumenName) {
		this.bumenName = bumenName == null ? null : bumenName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.yonghuId
	 * @return  the value of t_utaolun.yonghuId
	 * @mbggenerated
	 */
	public Integer getYonghuId() {
		return yonghuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.yonghuId
	 * @param yonghuId  the value for t_utaolun.yonghuId
	 * @mbggenerated
	 */
	public void setYonghuId(Integer yonghuId) {
		this.yonghuId = yonghuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.yonghuName
	 * @return  the value of t_utaolun.yonghuName
	 * @mbggenerated
	 */
	public String getYonghuName() {
		return yonghuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.yonghuName
	 * @param yonghuName  the value for t_utaolun.yonghuName
	 * @mbggenerated
	 */
	public void setYonghuName(String yonghuName) {
		this.yonghuName = yonghuName == null ? null : yonghuName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.yhbumenId
	 * @return  the value of t_utaolun.yhbumenId
	 * @mbggenerated
	 */
	public Integer getYhbumenId() {
		return yhbumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.yhbumenId
	 * @param yhbumenId  the value for t_utaolun.yhbumenId
	 * @mbggenerated
	 */
	public void setYhbumenId(Integer yhbumenId) {
		this.yhbumenId = yhbumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_utaolun.yhbumenName
	 * @return  the value of t_utaolun.yhbumenName
	 * @mbggenerated
	 */
	public String getYhbumenName() {
		return yhbumenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_utaolun.yhbumenName
	 * @param yhbumenName  the value for t_utaolun.yhbumenName
	 * @mbggenerated
	 */
	public void setYhbumenName(String yhbumenName) {
		this.yhbumenName = yhbumenName == null ? null : yhbumenName.trim();
	}
}