package com.model;

import java.util.Date;

public class Uxinxi {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiId
	 * @mbggenerated
	 */
	private Integer uxinxiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiName
	 * @mbggenerated
	 */
	private String uxinxiName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiMark
	 * @mbggenerated
	 */
	private String uxinxiMark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiMark1
	 * @mbggenerated
	 */
	private String uxinxiMark1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiMark2
	 * @mbggenerated
	 */
	private String uxinxiMark2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiImg
	 * @mbggenerated
	 */
	private String uxinxiImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiImgName
	 * @mbggenerated
	 */
	private String uxinxiImgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiDate
	 * @mbggenerated
	 */
	private Date uxinxiDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiType
	 * @mbggenerated
	 */
	private Integer uxinxiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxinxiType1
	 * @mbggenerated
	 */
	private Integer uxinxiType1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxtypeId
	 * @mbggenerated
	 */
	private Integer uxtypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.uxtypeName
	 * @mbggenerated
	 */
	private String uxtypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.userId
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.userName
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.bumenId
	 * @mbggenerated
	 */
	private Integer bumenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uxinxi.bumenName
	 * @mbggenerated
	 */
	private String bumenName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiId
	 * @return  the value of t_uxinxi.uxinxiId
	 * @mbggenerated
	 */
	public Integer getUxinxiId() {
		return uxinxiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiId
	 * @param uxinxiId  the value for t_uxinxi.uxinxiId
	 * @mbggenerated
	 */
	public void setUxinxiId(Integer uxinxiId) {
		this.uxinxiId = uxinxiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiName
	 * @return  the value of t_uxinxi.uxinxiName
	 * @mbggenerated
	 */
	public String getUxinxiName() {
		return uxinxiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiName
	 * @param uxinxiName  the value for t_uxinxi.uxinxiName
	 * @mbggenerated
	 */
	public void setUxinxiName(String uxinxiName) {
		this.uxinxiName = uxinxiName == null ? null : uxinxiName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiMark
	 * @return  the value of t_uxinxi.uxinxiMark
	 * @mbggenerated
	 */
	public String getUxinxiMark() {
		return uxinxiMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiMark
	 * @param uxinxiMark  the value for t_uxinxi.uxinxiMark
	 * @mbggenerated
	 */
	public void setUxinxiMark(String uxinxiMark) {
		this.uxinxiMark = uxinxiMark == null ? null : uxinxiMark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiMark1
	 * @return  the value of t_uxinxi.uxinxiMark1
	 * @mbggenerated
	 */
	public String getUxinxiMark1() {
		return uxinxiMark1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiMark1
	 * @param uxinxiMark1  the value for t_uxinxi.uxinxiMark1
	 * @mbggenerated
	 */
	public void setUxinxiMark1(String uxinxiMark1) {
		this.uxinxiMark1 = uxinxiMark1 == null ? null : uxinxiMark1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiMark2
	 * @return  the value of t_uxinxi.uxinxiMark2
	 * @mbggenerated
	 */
	public String getUxinxiMark2() {
		return uxinxiMark2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiMark2
	 * @param uxinxiMark2  the value for t_uxinxi.uxinxiMark2
	 * @mbggenerated
	 */
	public void setUxinxiMark2(String uxinxiMark2) {
		this.uxinxiMark2 = uxinxiMark2 == null ? null : uxinxiMark2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiImg
	 * @return  the value of t_uxinxi.uxinxiImg
	 * @mbggenerated
	 */
	public String getUxinxiImg() {
		return uxinxiImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiImg
	 * @param uxinxiImg  the value for t_uxinxi.uxinxiImg
	 * @mbggenerated
	 */
	public void setUxinxiImg(String uxinxiImg) {
		this.uxinxiImg = uxinxiImg == null ? null : uxinxiImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiImgName
	 * @return  the value of t_uxinxi.uxinxiImgName
	 * @mbggenerated
	 */
	public String getUxinxiImgName() {
		return uxinxiImgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiImgName
	 * @param uxinxiImgName  the value for t_uxinxi.uxinxiImgName
	 * @mbggenerated
	 */
	public void setUxinxiImgName(String uxinxiImgName) {
		this.uxinxiImgName = uxinxiImgName == null ? null : uxinxiImgName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiDate
	 * @return  the value of t_uxinxi.uxinxiDate
	 * @mbggenerated
	 */
	public Date getUxinxiDate() {
		return uxinxiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiDate
	 * @param uxinxiDate  the value for t_uxinxi.uxinxiDate
	 * @mbggenerated
	 */
	public void setUxinxiDate(Date uxinxiDate) {
		this.uxinxiDate = uxinxiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiType
	 * @return  the value of t_uxinxi.uxinxiType
	 * @mbggenerated
	 */
	public Integer getUxinxiType() {
		return uxinxiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiType
	 * @param uxinxiType  the value for t_uxinxi.uxinxiType
	 * @mbggenerated
	 */
	public void setUxinxiType(Integer uxinxiType) {
		this.uxinxiType = uxinxiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxinxiType1
	 * @return  the value of t_uxinxi.uxinxiType1
	 * @mbggenerated
	 */
	public Integer getUxinxiType1() {
		return uxinxiType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxinxiType1
	 * @param uxinxiType1  the value for t_uxinxi.uxinxiType1
	 * @mbggenerated
	 */
	public void setUxinxiType1(Integer uxinxiType1) {
		this.uxinxiType1 = uxinxiType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxtypeId
	 * @return  the value of t_uxinxi.uxtypeId
	 * @mbggenerated
	 */
	public Integer getUxtypeId() {
		return uxtypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxtypeId
	 * @param uxtypeId  the value for t_uxinxi.uxtypeId
	 * @mbggenerated
	 */
	public void setUxtypeId(Integer uxtypeId) {
		this.uxtypeId = uxtypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.uxtypeName
	 * @return  the value of t_uxinxi.uxtypeName
	 * @mbggenerated
	 */
	public String getUxtypeName() {
		return uxtypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.uxtypeName
	 * @param uxtypeName  the value for t_uxinxi.uxtypeName
	 * @mbggenerated
	 */
	public void setUxtypeName(String uxtypeName) {
		this.uxtypeName = uxtypeName == null ? null : uxtypeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.userId
	 * @return  the value of t_uxinxi.userId
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.userId
	 * @param userId  the value for t_uxinxi.userId
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.userName
	 * @return  the value of t_uxinxi.userName
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.userName
	 * @param userName  the value for t_uxinxi.userName
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.bumenId
	 * @return  the value of t_uxinxi.bumenId
	 * @mbggenerated
	 */
	public Integer getBumenId() {
		return bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.bumenId
	 * @param bumenId  the value for t_uxinxi.bumenId
	 * @mbggenerated
	 */
	public void setBumenId(Integer bumenId) {
		this.bumenId = bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uxinxi.bumenName
	 * @return  the value of t_uxinxi.bumenName
	 * @mbggenerated
	 */
	public String getBumenName() {
		return bumenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uxinxi.bumenName
	 * @param bumenName  the value for t_uxinxi.bumenName
	 * @mbggenerated
	 */
	public void setBumenName(String bumenName) {
		this.bumenName = bumenName == null ? null : bumenName.trim();
	}
}