package com.model;

import java.util.Date;

public class Uyijian {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianId
	 * @mbggenerated
	 */
	private Integer uyijianId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianName
	 * @mbggenerated
	 */
	private String uyijianName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianMark
	 * @mbggenerated
	 */
	private String uyijianMark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianMark1
	 * @mbggenerated
	 */
	private String uyijianMark1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianMark2
	 * @mbggenerated
	 */
	private String uyijianMark2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianImg
	 * @mbggenerated
	 */
	private String uyijianImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianImgName
	 * @mbggenerated
	 */
	private String uyijianImgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianDate
	 * @mbggenerated
	 */
	private Date uyijianDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianDate1
	 * @mbggenerated
	 */
	private Date uyijianDate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianType
	 * @mbggenerated
	 */
	private Integer uyijianType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.uyijianType1
	 * @mbggenerated
	 */
	private Integer uyijianType1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.userId
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.userName
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.bumenId
	 * @mbggenerated
	 */
	private Integer bumenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uyijian.bumenName
	 * @mbggenerated
	 */
	private String bumenName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianId
	 * @return  the value of t_uyijian.uyijianId
	 * @mbggenerated
	 */
	public Integer getUyijianId() {
		return uyijianId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianId
	 * @param uyijianId  the value for t_uyijian.uyijianId
	 * @mbggenerated
	 */
	public void setUyijianId(Integer uyijianId) {
		this.uyijianId = uyijianId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianName
	 * @return  the value of t_uyijian.uyijianName
	 * @mbggenerated
	 */
	public String getUyijianName() {
		return uyijianName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianName
	 * @param uyijianName  the value for t_uyijian.uyijianName
	 * @mbggenerated
	 */
	public void setUyijianName(String uyijianName) {
		this.uyijianName = uyijianName == null ? null : uyijianName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianMark
	 * @return  the value of t_uyijian.uyijianMark
	 * @mbggenerated
	 */
	public String getUyijianMark() {
		return uyijianMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianMark
	 * @param uyijianMark  the value for t_uyijian.uyijianMark
	 * @mbggenerated
	 */
	public void setUyijianMark(String uyijianMark) {
		this.uyijianMark = uyijianMark == null ? null : uyijianMark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianMark1
	 * @return  the value of t_uyijian.uyijianMark1
	 * @mbggenerated
	 */
	public String getUyijianMark1() {
		return uyijianMark1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianMark1
	 * @param uyijianMark1  the value for t_uyijian.uyijianMark1
	 * @mbggenerated
	 */
	public void setUyijianMark1(String uyijianMark1) {
		this.uyijianMark1 = uyijianMark1 == null ? null : uyijianMark1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianMark2
	 * @return  the value of t_uyijian.uyijianMark2
	 * @mbggenerated
	 */
	public String getUyijianMark2() {
		return uyijianMark2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianMark2
	 * @param uyijianMark2  the value for t_uyijian.uyijianMark2
	 * @mbggenerated
	 */
	public void setUyijianMark2(String uyijianMark2) {
		this.uyijianMark2 = uyijianMark2 == null ? null : uyijianMark2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianImg
	 * @return  the value of t_uyijian.uyijianImg
	 * @mbggenerated
	 */
	public String getUyijianImg() {
		return uyijianImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianImg
	 * @param uyijianImg  the value for t_uyijian.uyijianImg
	 * @mbggenerated
	 */
	public void setUyijianImg(String uyijianImg) {
		this.uyijianImg = uyijianImg == null ? null : uyijianImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianImgName
	 * @return  the value of t_uyijian.uyijianImgName
	 * @mbggenerated
	 */
	public String getUyijianImgName() {
		return uyijianImgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianImgName
	 * @param uyijianImgName  the value for t_uyijian.uyijianImgName
	 * @mbggenerated
	 */
	public void setUyijianImgName(String uyijianImgName) {
		this.uyijianImgName = uyijianImgName == null ? null : uyijianImgName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianDate
	 * @return  the value of t_uyijian.uyijianDate
	 * @mbggenerated
	 */
	public Date getUyijianDate() {
		return uyijianDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianDate
	 * @param uyijianDate  the value for t_uyijian.uyijianDate
	 * @mbggenerated
	 */
	public void setUyijianDate(Date uyijianDate) {
		this.uyijianDate = uyijianDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianDate1
	 * @return  the value of t_uyijian.uyijianDate1
	 * @mbggenerated
	 */
	public Date getUyijianDate1() {
		return uyijianDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianDate1
	 * @param uyijianDate1  the value for t_uyijian.uyijianDate1
	 * @mbggenerated
	 */
	public void setUyijianDate1(Date uyijianDate1) {
		this.uyijianDate1 = uyijianDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianType
	 * @return  the value of t_uyijian.uyijianType
	 * @mbggenerated
	 */
	public Integer getUyijianType() {
		return uyijianType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianType
	 * @param uyijianType  the value for t_uyijian.uyijianType
	 * @mbggenerated
	 */
	public void setUyijianType(Integer uyijianType) {
		this.uyijianType = uyijianType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.uyijianType1
	 * @return  the value of t_uyijian.uyijianType1
	 * @mbggenerated
	 */
	public Integer getUyijianType1() {
		return uyijianType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.uyijianType1
	 * @param uyijianType1  the value for t_uyijian.uyijianType1
	 * @mbggenerated
	 */
	public void setUyijianType1(Integer uyijianType1) {
		this.uyijianType1 = uyijianType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.userId
	 * @return  the value of t_uyijian.userId
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.userId
	 * @param userId  the value for t_uyijian.userId
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.userName
	 * @return  the value of t_uyijian.userName
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.userName
	 * @param userName  the value for t_uyijian.userName
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.bumenId
	 * @return  the value of t_uyijian.bumenId
	 * @mbggenerated
	 */
	public Integer getBumenId() {
		return bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.bumenId
	 * @param bumenId  the value for t_uyijian.bumenId
	 * @mbggenerated
	 */
	public void setBumenId(Integer bumenId) {
		this.bumenId = bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uyijian.bumenName
	 * @return  the value of t_uyijian.bumenName
	 * @mbggenerated
	 */
	public String getBumenName() {
		return bumenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uyijian.bumenName
	 * @param bumenName  the value for t_uyijian.bumenName
	 * @mbggenerated
	 */
	public void setBumenName(String bumenName) {
		this.bumenName = bumenName == null ? null : bumenName.trim();
	}
}