package com.model;

import java.util.Date;

public class Uzhannei {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiId
	 * @mbggenerated
	 */
	private Integer uzhanneiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiName
	 * @mbggenerated
	 */
	private String uzhanneiName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiMark
	 * @mbggenerated
	 */
	private String uzhanneiMark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiMark1
	 * @mbggenerated
	 */
	private String uzhanneiMark1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiMark2
	 * @mbggenerated
	 */
	private String uzhanneiMark2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiImg
	 * @mbggenerated
	 */
	private String uzhanneiImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiImgName
	 * @mbggenerated
	 */
	private String uzhanneiImgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiDate
	 * @mbggenerated
	 */
	private Date uzhanneiDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiDate1
	 * @mbggenerated
	 */
	private Date uzhanneiDate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiType
	 * @mbggenerated
	 */
	private Integer uzhanneiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uzhanneiType1
	 * @mbggenerated
	 */
	private Integer uzhanneiType1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uxtypeId
	 * @mbggenerated
	 */
	private Integer uxtypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.uxtypeName
	 * @mbggenerated
	 */
	private String uxtypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.userId
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.userName
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.shouuserId
	 * @mbggenerated
	 */
	private Integer shouuserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.shouuserName
	 * @mbggenerated
	 */
	private String shouuserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.bumenId
	 * @mbggenerated
	 */
	private Integer bumenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uzhannei.bumenName
	 * @mbggenerated
	 */
	private String bumenName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiId
	 * @return  the value of t_uzhannei.uzhanneiId
	 * @mbggenerated
	 */
	public Integer getUzhanneiId() {
		return uzhanneiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiId
	 * @param uzhanneiId  the value for t_uzhannei.uzhanneiId
	 * @mbggenerated
	 */
	public void setUzhanneiId(Integer uzhanneiId) {
		this.uzhanneiId = uzhanneiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiName
	 * @return  the value of t_uzhannei.uzhanneiName
	 * @mbggenerated
	 */
	public String getUzhanneiName() {
		return uzhanneiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiName
	 * @param uzhanneiName  the value for t_uzhannei.uzhanneiName
	 * @mbggenerated
	 */
	public void setUzhanneiName(String uzhanneiName) {
		this.uzhanneiName = uzhanneiName == null ? null : uzhanneiName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiMark
	 * @return  the value of t_uzhannei.uzhanneiMark
	 * @mbggenerated
	 */
	public String getUzhanneiMark() {
		return uzhanneiMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiMark
	 * @param uzhanneiMark  the value for t_uzhannei.uzhanneiMark
	 * @mbggenerated
	 */
	public void setUzhanneiMark(String uzhanneiMark) {
		this.uzhanneiMark = uzhanneiMark == null ? null : uzhanneiMark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiMark1
	 * @return  the value of t_uzhannei.uzhanneiMark1
	 * @mbggenerated
	 */
	public String getUzhanneiMark1() {
		return uzhanneiMark1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiMark1
	 * @param uzhanneiMark1  the value for t_uzhannei.uzhanneiMark1
	 * @mbggenerated
	 */
	public void setUzhanneiMark1(String uzhanneiMark1) {
		this.uzhanneiMark1 = uzhanneiMark1 == null ? null : uzhanneiMark1
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiMark2
	 * @return  the value of t_uzhannei.uzhanneiMark2
	 * @mbggenerated
	 */
	public String getUzhanneiMark2() {
		return uzhanneiMark2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiMark2
	 * @param uzhanneiMark2  the value for t_uzhannei.uzhanneiMark2
	 * @mbggenerated
	 */
	public void setUzhanneiMark2(String uzhanneiMark2) {
		this.uzhanneiMark2 = uzhanneiMark2 == null ? null : uzhanneiMark2
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiImg
	 * @return  the value of t_uzhannei.uzhanneiImg
	 * @mbggenerated
	 */
	public String getUzhanneiImg() {
		return uzhanneiImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiImg
	 * @param uzhanneiImg  the value for t_uzhannei.uzhanneiImg
	 * @mbggenerated
	 */
	public void setUzhanneiImg(String uzhanneiImg) {
		this.uzhanneiImg = uzhanneiImg == null ? null : uzhanneiImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiImgName
	 * @return  the value of t_uzhannei.uzhanneiImgName
	 * @mbggenerated
	 */
	public String getUzhanneiImgName() {
		return uzhanneiImgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiImgName
	 * @param uzhanneiImgName  the value for t_uzhannei.uzhanneiImgName
	 * @mbggenerated
	 */
	public void setUzhanneiImgName(String uzhanneiImgName) {
		this.uzhanneiImgName = uzhanneiImgName == null ? null : uzhanneiImgName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiDate
	 * @return  the value of t_uzhannei.uzhanneiDate
	 * @mbggenerated
	 */
	public Date getUzhanneiDate() {
		return uzhanneiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiDate
	 * @param uzhanneiDate  the value for t_uzhannei.uzhanneiDate
	 * @mbggenerated
	 */
	public void setUzhanneiDate(Date uzhanneiDate) {
		this.uzhanneiDate = uzhanneiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiDate1
	 * @return  the value of t_uzhannei.uzhanneiDate1
	 * @mbggenerated
	 */
	public Date getUzhanneiDate1() {
		return uzhanneiDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiDate1
	 * @param uzhanneiDate1  the value for t_uzhannei.uzhanneiDate1
	 * @mbggenerated
	 */
	public void setUzhanneiDate1(Date uzhanneiDate1) {
		this.uzhanneiDate1 = uzhanneiDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiType
	 * @return  the value of t_uzhannei.uzhanneiType
	 * @mbggenerated
	 */
	public Integer getUzhanneiType() {
		return uzhanneiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiType
	 * @param uzhanneiType  the value for t_uzhannei.uzhanneiType
	 * @mbggenerated
	 */
	public void setUzhanneiType(Integer uzhanneiType) {
		this.uzhanneiType = uzhanneiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uzhanneiType1
	 * @return  the value of t_uzhannei.uzhanneiType1
	 * @mbggenerated
	 */
	public Integer getUzhanneiType1() {
		return uzhanneiType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uzhanneiType1
	 * @param uzhanneiType1  the value for t_uzhannei.uzhanneiType1
	 * @mbggenerated
	 */
	public void setUzhanneiType1(Integer uzhanneiType1) {
		this.uzhanneiType1 = uzhanneiType1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uxtypeId
	 * @return  the value of t_uzhannei.uxtypeId
	 * @mbggenerated
	 */
	public Integer getUxtypeId() {
		return uxtypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uxtypeId
	 * @param uxtypeId  the value for t_uzhannei.uxtypeId
	 * @mbggenerated
	 */
	public void setUxtypeId(Integer uxtypeId) {
		this.uxtypeId = uxtypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.uxtypeName
	 * @return  the value of t_uzhannei.uxtypeName
	 * @mbggenerated
	 */
	public String getUxtypeName() {
		return uxtypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.uxtypeName
	 * @param uxtypeName  the value for t_uzhannei.uxtypeName
	 * @mbggenerated
	 */
	public void setUxtypeName(String uxtypeName) {
		this.uxtypeName = uxtypeName == null ? null : uxtypeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.userId
	 * @return  the value of t_uzhannei.userId
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.userId
	 * @param userId  the value for t_uzhannei.userId
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.userName
	 * @return  the value of t_uzhannei.userName
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.userName
	 * @param userName  the value for t_uzhannei.userName
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.shouuserId
	 * @return  the value of t_uzhannei.shouuserId
	 * @mbggenerated
	 */
	public Integer getShouuserId() {
		return shouuserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.shouuserId
	 * @param shouuserId  the value for t_uzhannei.shouuserId
	 * @mbggenerated
	 */
	public void setShouuserId(Integer shouuserId) {
		this.shouuserId = shouuserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.shouuserName
	 * @return  the value of t_uzhannei.shouuserName
	 * @mbggenerated
	 */
	public String getShouuserName() {
		return shouuserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.shouuserName
	 * @param shouuserName  the value for t_uzhannei.shouuserName
	 * @mbggenerated
	 */
	public void setShouuserName(String shouuserName) {
		this.shouuserName = shouuserName == null ? null : shouuserName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.bumenId
	 * @return  the value of t_uzhannei.bumenId
	 * @mbggenerated
	 */
	public Integer getBumenId() {
		return bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.bumenId
	 * @param bumenId  the value for t_uzhannei.bumenId
	 * @mbggenerated
	 */
	public void setBumenId(Integer bumenId) {
		this.bumenId = bumenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uzhannei.bumenName
	 * @return  the value of t_uzhannei.bumenName
	 * @mbggenerated
	 */
	public String getBumenName() {
		return bumenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uzhannei.bumenName
	 * @param bumenName  the value for t_uzhannei.bumenName
	 * @mbggenerated
	 */
	public void setBumenName(String bumenName) {
		this.bumenName = bumenName == null ? null : bumenName.trim();
	}
}