package com.model;

public class Yhbumen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhbumen.yhbumenId
     *
     * @mbggenerated
     */
    private Integer yhbumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhbumen.yhbumenName
     *
     * @mbggenerated
     */
    private String yhbumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhbumen.yhbumenMark
     *
     * @mbggenerated
     */
    private String yhbumenMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhbumen.yhbumenMark1
     *
     * @mbggenerated
     */
    private String yhbumenMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhbumen.yhbumenMark2
     *
     * @mbggenerated
     */
    private Integer yhbumenMark2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhbumen.yhbumenId
     *
     * @return the value of t_yhbumen.yhbumenId
     *
     * @mbggenerated
     */
    public Integer getYhbumenId() {
        return yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhbumen.yhbumenId
     *
     * @param yhbumenId the value for t_yhbumen.yhbumenId
     *
     * @mbggenerated
     */
    public void setYhbumenId(Integer yhbumenId) {
        this.yhbumenId = yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhbumen.yhbumenName
     *
     * @return the value of t_yhbumen.yhbumenName
     *
     * @mbggenerated
     */
    public String getYhbumenName() {
        return yhbumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhbumen.yhbumenName
     *
     * @param yhbumenName the value for t_yhbumen.yhbumenName
     *
     * @mbggenerated
     */
    public void setYhbumenName(String yhbumenName) {
        this.yhbumenName = yhbumenName == null ? null : yhbumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhbumen.yhbumenMark
     *
     * @return the value of t_yhbumen.yhbumenMark
     *
     * @mbggenerated
     */
    public String getYhbumenMark() {
        return yhbumenMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhbumen.yhbumenMark
     *
     * @param yhbumenMark the value for t_yhbumen.yhbumenMark
     *
     * @mbggenerated
     */
    public void setYhbumenMark(String yhbumenMark) {
        this.yhbumenMark = yhbumenMark == null ? null : yhbumenMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhbumen.yhbumenMark1
     *
     * @return the value of t_yhbumen.yhbumenMark1
     *
     * @mbggenerated
     */
    public String getYhbumenMark1() {
        return yhbumenMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhbumen.yhbumenMark1
     *
     * @param yhbumenMark1 the value for t_yhbumen.yhbumenMark1
     *
     * @mbggenerated
     */
    public void setYhbumenMark1(String yhbumenMark1) {
        this.yhbumenMark1 = yhbumenMark1 == null ? null : yhbumenMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhbumen.yhbumenMark2
     *
     * @return the value of t_yhbumen.yhbumenMark2
     *
     * @mbggenerated
     */
    public Integer getYhbumenMark2() {
        return yhbumenMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhbumen.yhbumenMark2
     *
     * @param yhbumenMark2 the value for t_yhbumen.yhbumenMark2
     *
     * @mbggenerated
     */
    public void setYhbumenMark2(Integer yhbumenMark2) {
        this.yhbumenMark2 = yhbumenMark2;
    }
}