package com.model;

import java.util.Date;

public class Yonghu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuPassword
     *
     * @mbggenerated
     */
    private String yonghuPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuXingming
     *
     * @mbggenerated
     */
    private String yonghuXingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuSex
     *
     * @mbggenerated
     */
    private Integer yonghuSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuAge
     *
     * @mbggenerated
     */
    private Integer yonghuAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuPhone
     *
     * @mbggenerated
     */
    private String yonghuPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMark1
     *
     * @mbggenerated
     */
    private String yonghuMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMark2
     *
     * @mbggenerated
     */
    private String yonghuMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMark3
     *
     * @mbggenerated
     */
    private String yonghuMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMark4
     *
     * @mbggenerated
     */
    private String yonghuMark4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuDate1
     *
     * @mbggenerated
     */
    private Date yonghuDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuDate2
     *
     * @mbggenerated
     */
    private Date yonghuDate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuType1
     *
     * @mbggenerated
     */
    private Integer yonghuType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuType2
     *
     * @mbggenerated
     */
    private Integer yonghuType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuImg
     *
     * @mbggenerated
     */
    private String yonghuImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuImgName
     *
     * @mbggenerated
     */
    private String yonghuImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yhbumenId
     *
     * @mbggenerated
     */
    private Integer yhbumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yhbumenName
     *
     * @mbggenerated
     */
    private String yhbumenName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuId
     *
     * @return the value of t_yonghu.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuId
     *
     * @param yonghuId the value for t_yonghu.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuName
     *
     * @return the value of t_yonghu.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuName
     *
     * @param yonghuName the value for t_yonghu.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuPassword
     *
     * @return the value of t_yonghu.yonghuPassword
     *
     * @mbggenerated
     */
    public String getYonghuPassword() {
        return yonghuPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuPassword
     *
     * @param yonghuPassword the value for t_yonghu.yonghuPassword
     *
     * @mbggenerated
     */
    public void setYonghuPassword(String yonghuPassword) {
        this.yonghuPassword = yonghuPassword == null ? null : yonghuPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuXingming
     *
     * @return the value of t_yonghu.yonghuXingming
     *
     * @mbggenerated
     */
    public String getYonghuXingming() {
        return yonghuXingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuXingming
     *
     * @param yonghuXingming the value for t_yonghu.yonghuXingming
     *
     * @mbggenerated
     */
    public void setYonghuXingming(String yonghuXingming) {
        this.yonghuXingming = yonghuXingming == null ? null : yonghuXingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuSex
     *
     * @return the value of t_yonghu.yonghuSex
     *
     * @mbggenerated
     */
    public Integer getYonghuSex() {
        return yonghuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuSex
     *
     * @param yonghuSex the value for t_yonghu.yonghuSex
     *
     * @mbggenerated
     */
    public void setYonghuSex(Integer yonghuSex) {
        this.yonghuSex = yonghuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuAge
     *
     * @return the value of t_yonghu.yonghuAge
     *
     * @mbggenerated
     */
    public Integer getYonghuAge() {
        return yonghuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuAge
     *
     * @param yonghuAge the value for t_yonghu.yonghuAge
     *
     * @mbggenerated
     */
    public void setYonghuAge(Integer yonghuAge) {
        this.yonghuAge = yonghuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuPhone
     *
     * @return the value of t_yonghu.yonghuPhone
     *
     * @mbggenerated
     */
    public String getYonghuPhone() {
        return yonghuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuPhone
     *
     * @param yonghuPhone the value for t_yonghu.yonghuPhone
     *
     * @mbggenerated
     */
    public void setYonghuPhone(String yonghuPhone) {
        this.yonghuPhone = yonghuPhone == null ? null : yonghuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMark1
     *
     * @return the value of t_yonghu.yonghuMark1
     *
     * @mbggenerated
     */
    public String getYonghuMark1() {
        return yonghuMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMark1
     *
     * @param yonghuMark1 the value for t_yonghu.yonghuMark1
     *
     * @mbggenerated
     */
    public void setYonghuMark1(String yonghuMark1) {
        this.yonghuMark1 = yonghuMark1 == null ? null : yonghuMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMark2
     *
     * @return the value of t_yonghu.yonghuMark2
     *
     * @mbggenerated
     */
    public String getYonghuMark2() {
        return yonghuMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMark2
     *
     * @param yonghuMark2 the value for t_yonghu.yonghuMark2
     *
     * @mbggenerated
     */
    public void setYonghuMark2(String yonghuMark2) {
        this.yonghuMark2 = yonghuMark2 == null ? null : yonghuMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMark3
     *
     * @return the value of t_yonghu.yonghuMark3
     *
     * @mbggenerated
     */
    public String getYonghuMark3() {
        return yonghuMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMark3
     *
     * @param yonghuMark3 the value for t_yonghu.yonghuMark3
     *
     * @mbggenerated
     */
    public void setYonghuMark3(String yonghuMark3) {
        this.yonghuMark3 = yonghuMark3 == null ? null : yonghuMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMark4
     *
     * @return the value of t_yonghu.yonghuMark4
     *
     * @mbggenerated
     */
    public String getYonghuMark4() {
        return yonghuMark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMark4
     *
     * @param yonghuMark4 the value for t_yonghu.yonghuMark4
     *
     * @mbggenerated
     */
    public void setYonghuMark4(String yonghuMark4) {
        this.yonghuMark4 = yonghuMark4 == null ? null : yonghuMark4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuDate1
     *
     * @return the value of t_yonghu.yonghuDate1
     *
     * @mbggenerated
     */
    public Date getYonghuDate1() {
        return yonghuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuDate1
     *
     * @param yonghuDate1 the value for t_yonghu.yonghuDate1
     *
     * @mbggenerated
     */
    public void setYonghuDate1(Date yonghuDate1) {
        this.yonghuDate1 = yonghuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuDate2
     *
     * @return the value of t_yonghu.yonghuDate2
     *
     * @mbggenerated
     */
    public Date getYonghuDate2() {
        return yonghuDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuDate2
     *
     * @param yonghuDate2 the value for t_yonghu.yonghuDate2
     *
     * @mbggenerated
     */
    public void setYonghuDate2(Date yonghuDate2) {
        this.yonghuDate2 = yonghuDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuType1
     *
     * @return the value of t_yonghu.yonghuType1
     *
     * @mbggenerated
     */
    public Integer getYonghuType1() {
        return yonghuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuType1
     *
     * @param yonghuType1 the value for t_yonghu.yonghuType1
     *
     * @mbggenerated
     */
    public void setYonghuType1(Integer yonghuType1) {
        this.yonghuType1 = yonghuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuType2
     *
     * @return the value of t_yonghu.yonghuType2
     *
     * @mbggenerated
     */
    public Integer getYonghuType2() {
        return yonghuType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuType2
     *
     * @param yonghuType2 the value for t_yonghu.yonghuType2
     *
     * @mbggenerated
     */
    public void setYonghuType2(Integer yonghuType2) {
        this.yonghuType2 = yonghuType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuImg
     *
     * @return the value of t_yonghu.yonghuImg
     *
     * @mbggenerated
     */
    public String getYonghuImg() {
        return yonghuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuImg
     *
     * @param yonghuImg the value for t_yonghu.yonghuImg
     *
     * @mbggenerated
     */
    public void setYonghuImg(String yonghuImg) {
        this.yonghuImg = yonghuImg == null ? null : yonghuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuImgName
     *
     * @return the value of t_yonghu.yonghuImgName
     *
     * @mbggenerated
     */
    public String getYonghuImgName() {
        return yonghuImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuImgName
     *
     * @param yonghuImgName the value for t_yonghu.yonghuImgName
     *
     * @mbggenerated
     */
    public void setYonghuImgName(String yonghuImgName) {
        this.yonghuImgName = yonghuImgName == null ? null : yonghuImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yhroleId
     *
     * @return the value of t_yonghu.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yhroleId
     *
     * @param yhroleId the value for t_yonghu.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yhroleName
     *
     * @return the value of t_yonghu.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yhroleName
     *
     * @param yhroleName the value for t_yonghu.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yhbumenId
     *
     * @return the value of t_yonghu.yhbumenId
     *
     * @mbggenerated
     */
    public Integer getYhbumenId() {
        return yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yhbumenId
     *
     * @param yhbumenId the value for t_yonghu.yhbumenId
     *
     * @mbggenerated
     */
    public void setYhbumenId(Integer yhbumenId) {
        this.yhbumenId = yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yhbumenName
     *
     * @return the value of t_yonghu.yhbumenName
     *
     * @mbggenerated
     */
    public String getYhbumenName() {
        return yhbumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yhbumenName
     *
     * @param yhbumenName the value for t_yonghu.yhbumenName
     *
     * @mbggenerated
     */
    public void setYhbumenName(String yhbumenName) {
        this.yhbumenName = yhbumenName == null ? null : yhbumenName.trim();
    }
}