package com.model;

import java.util.Date;

public class Yxinxi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiId
     *
     * @mbggenerated
     */
    private Integer yxinxiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiName
     *
     * @mbggenerated
     */
    private String yxinxiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiMark
     *
     * @mbggenerated
     */
    private String yxinxiMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiMark1
     *
     * @mbggenerated
     */
    private String yxinxiMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiMark2
     *
     * @mbggenerated
     */
    private String yxinxiMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiImg
     *
     * @mbggenerated
     */
    private String yxinxiImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiImgName
     *
     * @mbggenerated
     */
    private String yxinxiImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiDate
     *
     * @mbggenerated
     */
    private Date yxinxiDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiType
     *
     * @mbggenerated
     */
    private Integer yxinxiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiType1
     *
     * @mbggenerated
     */
    private Integer yxinxiType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxtypeId
     *
     * @mbggenerated
     */
    private Integer yxtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxtypeName
     *
     * @mbggenerated
     */
    private String yxtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yhbumenId
     *
     * @mbggenerated
     */
    private Integer yhbumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yhbumenName
     *
     * @mbggenerated
     */
    private String yhbumenName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiId
     *
     * @return the value of t_yxinxi.yxinxiId
     *
     * @mbggenerated
     */
    public Integer getYxinxiId() {
        return yxinxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiId
     *
     * @param yxinxiId the value for t_yxinxi.yxinxiId
     *
     * @mbggenerated
     */
    public void setYxinxiId(Integer yxinxiId) {
        this.yxinxiId = yxinxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiName
     *
     * @return the value of t_yxinxi.yxinxiName
     *
     * @mbggenerated
     */
    public String getYxinxiName() {
        return yxinxiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiName
     *
     * @param yxinxiName the value for t_yxinxi.yxinxiName
     *
     * @mbggenerated
     */
    public void setYxinxiName(String yxinxiName) {
        this.yxinxiName = yxinxiName == null ? null : yxinxiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiMark
     *
     * @return the value of t_yxinxi.yxinxiMark
     *
     * @mbggenerated
     */
    public String getYxinxiMark() {
        return yxinxiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiMark
     *
     * @param yxinxiMark the value for t_yxinxi.yxinxiMark
     *
     * @mbggenerated
     */
    public void setYxinxiMark(String yxinxiMark) {
        this.yxinxiMark = yxinxiMark == null ? null : yxinxiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiMark1
     *
     * @return the value of t_yxinxi.yxinxiMark1
     *
     * @mbggenerated
     */
    public String getYxinxiMark1() {
        return yxinxiMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiMark1
     *
     * @param yxinxiMark1 the value for t_yxinxi.yxinxiMark1
     *
     * @mbggenerated
     */
    public void setYxinxiMark1(String yxinxiMark1) {
        this.yxinxiMark1 = yxinxiMark1 == null ? null : yxinxiMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiMark2
     *
     * @return the value of t_yxinxi.yxinxiMark2
     *
     * @mbggenerated
     */
    public String getYxinxiMark2() {
        return yxinxiMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiMark2
     *
     * @param yxinxiMark2 the value for t_yxinxi.yxinxiMark2
     *
     * @mbggenerated
     */
    public void setYxinxiMark2(String yxinxiMark2) {
        this.yxinxiMark2 = yxinxiMark2 == null ? null : yxinxiMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiImg
     *
     * @return the value of t_yxinxi.yxinxiImg
     *
     * @mbggenerated
     */
    public String getYxinxiImg() {
        return yxinxiImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiImg
     *
     * @param yxinxiImg the value for t_yxinxi.yxinxiImg
     *
     * @mbggenerated
     */
    public void setYxinxiImg(String yxinxiImg) {
        this.yxinxiImg = yxinxiImg == null ? null : yxinxiImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiImgName
     *
     * @return the value of t_yxinxi.yxinxiImgName
     *
     * @mbggenerated
     */
    public String getYxinxiImgName() {
        return yxinxiImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiImgName
     *
     * @param yxinxiImgName the value for t_yxinxi.yxinxiImgName
     *
     * @mbggenerated
     */
    public void setYxinxiImgName(String yxinxiImgName) {
        this.yxinxiImgName = yxinxiImgName == null ? null : yxinxiImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiDate
     *
     * @return the value of t_yxinxi.yxinxiDate
     *
     * @mbggenerated
     */
    public Date getYxinxiDate() {
        return yxinxiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiDate
     *
     * @param yxinxiDate the value for t_yxinxi.yxinxiDate
     *
     * @mbggenerated
     */
    public void setYxinxiDate(Date yxinxiDate) {
        this.yxinxiDate = yxinxiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiType
     *
     * @return the value of t_yxinxi.yxinxiType
     *
     * @mbggenerated
     */
    public Integer getYxinxiType() {
        return yxinxiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiType
     *
     * @param yxinxiType the value for t_yxinxi.yxinxiType
     *
     * @mbggenerated
     */
    public void setYxinxiType(Integer yxinxiType) {
        this.yxinxiType = yxinxiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiType1
     *
     * @return the value of t_yxinxi.yxinxiType1
     *
     * @mbggenerated
     */
    public Integer getYxinxiType1() {
        return yxinxiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiType1
     *
     * @param yxinxiType1 the value for t_yxinxi.yxinxiType1
     *
     * @mbggenerated
     */
    public void setYxinxiType1(Integer yxinxiType1) {
        this.yxinxiType1 = yxinxiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxtypeId
     *
     * @return the value of t_yxinxi.yxtypeId
     *
     * @mbggenerated
     */
    public Integer getYxtypeId() {
        return yxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxtypeId
     *
     * @param yxtypeId the value for t_yxinxi.yxtypeId
     *
     * @mbggenerated
     */
    public void setYxtypeId(Integer yxtypeId) {
        this.yxtypeId = yxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxtypeName
     *
     * @return the value of t_yxinxi.yxtypeName
     *
     * @mbggenerated
     */
    public String getYxtypeName() {
        return yxtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxtypeName
     *
     * @param yxtypeName the value for t_yxinxi.yxtypeName
     *
     * @mbggenerated
     */
    public void setYxtypeName(String yxtypeName) {
        this.yxtypeName = yxtypeName == null ? null : yxtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yonghuId
     *
     * @return the value of t_yxinxi.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yonghuId
     *
     * @param yonghuId the value for t_yxinxi.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yonghuName
     *
     * @return the value of t_yxinxi.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yonghuName
     *
     * @param yonghuName the value for t_yxinxi.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yhbumenId
     *
     * @return the value of t_yxinxi.yhbumenId
     *
     * @mbggenerated
     */
    public Integer getYhbumenId() {
        return yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yhbumenId
     *
     * @param yhbumenId the value for t_yxinxi.yhbumenId
     *
     * @mbggenerated
     */
    public void setYhbumenId(Integer yhbumenId) {
        this.yhbumenId = yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yhbumenName
     *
     * @return the value of t_yxinxi.yhbumenName
     *
     * @mbggenerated
     */
    public String getYhbumenName() {
        return yhbumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yhbumenName
     *
     * @param yhbumenName the value for t_yxinxi.yhbumenName
     *
     * @mbggenerated
     */
    public void setYhbumenName(String yhbumenName) {
        this.yhbumenName = yhbumenName == null ? null : yhbumenName.trim();
    }
}