package com.mapper;

import com.model.Spjin;
import com.model.Spjin;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SpjinMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_spjin
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer spjinId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_spjin
	 * @mbggenerated
	 */
	int insert(Spjin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_spjin
	 * @mbggenerated
	 */
	Spjin selectByPrimaryKey(Integer spjinId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_spjin
	 * @mbggenerated
	 */
	List<Spjin> selectAll(@Param("spjin")Spjin record,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_spjin
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Spjin record);
}