package com.mapper;

import com.model.Sptype;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SptypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sptype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sptypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sptype
     *
     * @mbggenerated
     */
    int insert(Sptype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sptype
     *
     * @mbggenerated
     */
    Sptype selectByPrimaryKey(Integer sptypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sptype
     *
     * @mbggenerated
     */
    List<Sptype> selectAll(@Param("sptype")Sptype record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sptype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sptype record);
}