package com.mapper;

import com.model.Utaolun;
import com.model.Utaolun;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UtaolunMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_utaolun
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer utaolunId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_utaolun
	 * @mbggenerated
	 */
	int insert(Utaolun record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_utaolun
	 * @mbggenerated
	 */
	Utaolun selectByPrimaryKey(Integer utaolunId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_utaolun
	 * @mbggenerated
	 */
	List<Utaolun> selectAll(@Param("utaolun")Utaolun record,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_utaolun
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Utaolun record);
}