package com.mapper;

import com.model.Uzhannei;
import com.model.Uzhannei;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UzhanneiMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uzhannei
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer uzhanneiId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uzhannei
	 * @mbggenerated
	 */
	int insert(Uzhannei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uzhannei
	 * @mbggenerated
	 */
	Uzhannei selectByPrimaryKey(Integer uzhanneiId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uzhannei
	 * @mbggenerated
	 */
	List<Uzhannei> selectAll(@Param("uzhannei")Uzhannei record,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uzhannei
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Uzhannei record);
}