package com.mapper;

import com.model.Yhbumen;
import com.model.Yhbumen;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface YhbumenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhbumen
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer yhbumenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhbumen
     *
     * @mbggenerated
     */
    int insert(Yhbumen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhbumen
     *
     * @mbggenerated
     */
    Yhbumen selectByPrimaryKey(Integer yhbumenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhbumen
     *
     * @mbggenerated
     */
    List<Yhbumen> selectAll(@Param("yhbumen")Yhbumen record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhbumen
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yhbumen record);
}